docs(cloudevents): try cloudevents-nodejs with kn
knative/docs pull request #2827
Opened 2020-09-17 20:49 UTC by lance

Adds tabbed instructions for deploying and deleting the Node.js cloudevents
sample using the `kn` CLI.

Signed-off-by: Lance Ball <lball@redhat.com>

2020-09-20 00:06 UTC, csantanapr commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +{{< tabs name="cloudevents_rust_deploy" default="kn" >}} {{% tab name="yaml" %}}
```suggestion
{{< tabs name="cloudevents_nodejs_deploy" default="kn" >}} {{% tab name="yaml" %}}
```

2020-09-20 00:06 UTC, csantanapr commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +{{< tabs name="cloudevents_rust_delete" default="kn" >}} {{% tab name="yaml" %}}
```suggestion
{{< tabs name="cloudevents_nodejs_delete" default="kn" >}} {{% tab name="yaml" %}}
```

2020-11-03 14:56 UTC, abrennan89 commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +In `index.js`, you will see two key functions for the different modes of operation:
```suggestion
In the `index.js` object, you will see two key functions for the different modes of operation:
```

2020-11-03 14:56 UTC, abrennan89 commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +In the `Dockerfile`, you will see how the dependencies are installed using npm.
```suggestion
In the `Dockerfile`, you can see how the dependencies are installed using npm.
```

2020-11-03 14:57 UTC, abrennan89 commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +To deploy the Knative service, look in `service.yaml` and replace `<registry/repository/image:tag>` with the image just created.
```suggestion
To deploy the Knative service, replace `<registry/repository/image:tag>` with the image just created in the `service.yaml` file.
```

2020-11-03 14:59 UTC, abrennan89 requested changes
Some suggestions, otherwise looks good!

2020-11-03 20:05 UTC, lance commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +In `index.js`, you will see two key functions for the different modes of operation:
Done

2020-11-03 20:05 UTC, lance commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +In the `Dockerfile`, you will see how the dependencies are installed using npm.
Done

2020-11-03 20:05 UTC, lance commented on docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
> +To deploy the Knative service, look in `service.yaml` and replace `<registry/repository/image:tag>` with the image just created.
Done

2020-11-03 20:05 UTC, lance commented
@abrennan89 all set - ptal

2020-11-03 20:37 UTC, abrennan89 commented
@mattmoor any idea why the test is failing?

2020-11-03 20:38 UTC, abrennan89 approved these changes

2020-11-03 21:25 UTC, mattmoor commented
🤔  cc @markusthoemmes

2020-11-03 21:26 UTC, mattmoor commented
It's complaining about files outside of the PR, so it shouldn't block this.

2020-11-04 16:58 UTC, abrennan89 approved these changes
/lgtm

2020-11-04 17:09 UTC, merged