hello world java with tabs
knative/docs pull request #2833
Opened 2020-09-19 02:09 UTC by itsmurugappan

## Proposed Changes 

- hello world java example with tabs

2020-09-21 17:54 UTC, mpetason commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +1. After the build has completed and the container is pushed to docker hub, you
```suggestion
1. After the build has completed and the container is pushed to Docker Hub, you
```

Capitalized for consistency

2020-10-01 22:55 UTC, maximilien approved these changes
LGTM

2020-10-01 22:55 UTC, maximilien commented
/test pull-knative-docs-unit-tests

2020-10-08 01:53 UTC, tcnghia commented
```

=== RUN   TestDocSrc/java-spring     sampleconsistency_test.go:97: README.md file is missing line 0 ('package com.example.helloworld;') from file '../../docs/serving/samples/hello-world/helloworld-java-spring/src/main/java/com/example/helloworld/HelloworldApplication.java'         Additional info:         All files required for running sample apps are checked against README.md, the content of source files should be identical with what's in README.md file, the list of the files to be verified is the same set of files used for running sample apps, they are configured in `/test/sampleapp/config.yaml`. If an exception is needed the file can be configured to be copied as a separate step in `PreCommand` such as: https://github.com/knative/docs/blob/65f7b402fee7f94dfbd9e4512ef3beed7b85de66/test/sampleapp/config.yaml#L4     --- FAIL: TestDocSrc/java-spring (0.00s) | === RUN   TestDocSrc/java-spring     sampleconsistency_test.go:97: README.md file is missing line 0 ('package com.example.helloworld;') from file '../../docs/serving/samples/hello-world/helloworld-java-spring/src/main/java/com/example/helloworld/HelloworldApplication.java'         Additional info:         All files required for running sample apps are checked against README.md, the content of source files should be identical with what's in README.md file, the list of the files to be verified is the same set of files used for running sample apps, they are configured in `/test/sampleapp/config.yaml`. If an exception is needed the file can be configured to be copied as a separate step in `PreCommand` such as: https://github.com/knative/docs/blob/65f7b402fee7f94dfbd9e4512ef3beed7b85de66/test/sampleapp/config.yaml#L4     --- FAIL: TestDocSrc/java-spring (0.00s)
-- | --
=== RUN   TestDocSrc/java-spring     sampleconsistency_test.go:97: README.md file is missing line 0 ('package com.example.helloworld;') from file '../../docs/serving/samples/hello-world/helloworld-java-spring/src/main/java/com/example/helloworld/HelloworldApplication.java'         Additional info:         All files required for running sample apps are checked against README.md, the content of source files should be identical with what's in README.md file, the list of the files to be verified is the same set of files used for running sample apps, they are configured in `/test/sampleapp/config.yaml`. If an exception is needed the file can be configured to be copied as a separate step in `PreCommand` such as: https://github.com/knative/docs/blob/65f7b402fee7f94dfbd9e4512ef3beed7b85de66/test/sampleapp/config.yaml#L4     --- FAIL: TestDocSrc/java-spring (0.00s)
 


```

2020-10-09 20:19 UTC, itsmurugappan commented
[pr](https://github.com/knative/docs/pull/2832) takes care of this test failure, once that is merged , i can rebase which will fix the test

2020-11-03 15:10 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +The sample app reads a TARGET environment variable, and prints Hello ${TARGET}!. If TARGET is not specified, World is used as the default value.
```suggestion
The sample app reads a `TARGET` environment variable, and prints `Hello ${TARGET}!`.
If `TARGET` is not specified, `World` is used as the default value.
```

2020-11-03 15:12 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +- (optional) The Knatice CLI client [kn](https://github.com/knative/client/releases) that simplifies the deployment. Alternative you can also use `kubectl` and apply resource files directly.
```suggestion
- Optional: the Knative CLI client [kn](https://github.com/knative/client/releases) can be used to simplify deployment. Alternatively, you can use `kubectl`, and apply resource files directly.
```

2020-11-03 15:12 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +## Build
```suggestion
## Building the sample app
```

2020-11-03 15:13 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   commands:
```suggestion
1. From the console, create a new, empty web project by using the curl and unzip
   commands:
```

2020-11-03 15:13 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   If you don't have curl installed, you can accomplish the same by visiting the
```suggestion
   If you don't have `curl` installed, you can accomplish the same by visiting the
```

2020-11-03 15:14 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   provide the TARGET environment variable:
```suggestion
   provide the `TARGET` environment variable:
```

2020-11-03 15:15 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   [Creating Smaller Java Image using Docker Multi-stage Build](http://blog.arungupta.me/smaller-java-image-docker-multi-stage-build/).
```suggestion
1. In your project directory, create a file named `Dockerfile` and copy the code
   block below into it:
```

2020-11-03 15:16 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +folder) you're ready to build and deploy the sample app.
```suggestion
For detailed instructions on dockerizing a Spring Boot app, see [Spring Boot with Docker](https://spring.io/guides/gs/spring-boot-docker/).

For additional information on multi-stage docker builds for Java, see [Creating Smaller Java Image using Docker Multi-stage Build](http://blog.arungupta.me/smaller-java-image-docker-multi-stage-build/).
```

2020-11-03 15:16 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +Once you have recreated the sample code files (or used the files in the sample
No need for this line, the title of the section already tells us we're building an app. Removed lines.

2020-11-03 15:17 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +folder) you're ready to build and deploy the sample app.
Moved these links until the end of the procedure. Generally good practice to only have steps in a procedure and any links, refs etc go in an Additional Resources section or similar at the end.

2020-11-03 15:21 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   username:
```suggestion
**NOTE:** Use Docker to build the sample code into a container. To build and push with Docker Hub, run these commands replacing `{username}` with your Docker Hub username.

1. Build the sample code into a container, then push the container to the Docker registry:
```

2020-11-03 15:22 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +1. After the build has completed and the container is pushed to Docker Hub, you
```suggestion
After the build has completed and the container is pushed to Docker Hub, you
```

2020-11-03 15:22 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +## Deploying
```suggestion
## Deploying the app
```

2020-11-03 15:23 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   - Automatically scale your pods up and down (including to zero active pods).
```suggestion
   - Automatically scale your pods up and down, including scaling down to zero active pods.
```

2020-11-03 15:23 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +1. Run one of the followings commands to find the domain URL for your service.
```suggestion
1. Find the domain URL for your service:
```

2020-11-03 15:24 UTC, abrennan89 commented on docs/serving/samples/hello-world/helloworld-java-spring/index.md
> +   the URL below with the URL returned in the previous command.
```suggestion
1. Make a request to your app and observe the result. Replace
   the URL below with the URL returned in the previous command.
```

2020-11-03 15:24 UTC, abrennan89 requested changes
Some minor comments

2020-11-04 18:12 UTC, abrennan89 commented
> [pr](https://github.com/knative/docs/pull/2832) takes care of this test failure, once that is merged , i can rebase which will fix the test

@itsmurugappan Thanks for the updates! Do we have a dependency on merging #2832 first, or is this PR ready to merge now?
@rhuss can you take a look at that PR please, it looks like it needs a rebase.

2020-11-04 18:12 UTC, abrennan89 approved these changes
/hold
/approve
/lgtm

2020-11-04 18:14 UTC, itsmurugappan commented
This can be merged now as I have fixed the Readme to pass the tests.

2020-11-04 18:15 UTC, abrennan89 commented
Thanks @itsmurugappan - does this need to be cherry-picked to any older branches?

2020-11-04 18:24 UTC, merged