Add events to Cloud Run for Anthos description
knative/docs pull request #3026
Opened 2020-11-11 20:28 UTC by grantr

Now that Cloud Run for Anthos supports eventing (in beta), I added it to the description of the CRfA offering.

## Proposed Changes

- add eventing functionality to CRfA description

2020-12-16 20:29 UTC, abrennan89 commented on docs/knative-offerings.md
> +- [Google Cloud Run for Anthos](https://cloud.google.com/run/docs/gke/setup): Extend Google Kubernetes Engine with a flexible serverless development platform. With Cloud Run for Anthos, you get the o
```suggestion
- [Google Cloud Run for Anthos](https://cloud.google.com/run/docs/gke/setup): Extend Google Kubernetes Engine with a flexible serverless development platform. With Cloud Run for Anthos, you get the operational flexibility of Kubernetes with the developer experience of serverless, allowing you to deploy and manage Knative-based services on your own cluster, and trigger them with events from Google, 3rd-party sources, and your own applications.
```

2020-12-16 20:29 UTC, abrennan89 requested changes
@grantr suggested minor tweaks :slightly_smiling_face:

2021-03-05 22:06 UTC, abrennan89 approved these changes
/lgtm

2021-03-05 22:06 UTC, abrennan89 commented
@googlebot I consent.

2021-03-05 22:07 UTC, abrennan89 commented
@googlebot I fixed it.

2021-03-05 22:07 UTC, abrennan89 commented
@googlebot I consent

2021-03-05 22:09 UTC, abrennan89 commented
@grantr hadn't heard back on this one so I committed the suggestion myself, but now I can't fix the CLA. If you fix it this should merge.

2021-03-17 20:01 UTC, abrennan89 commented
/retest

2021-03-17 20:44 UTC, grantr commented
All contributors have previously signed the CLA.

2021-03-17 20:54 UTC, merged