Update eventing broker README
knative/docs pull request #3057
Opened 2020-11-22 21:50 UTC by xtreme-sameer-vohra

## Proposed Changes 
Add RabbitMQ as an example of a channel provider

2020-11-23 18:30 UTC, vaikas commented
/ok-to-test

2020-11-24 17:09 UTC, xtreme-sameer-vohra commented
@googlebot I fixed it.

2020-12-03 21:39 UTC, abrennan89 commented on docs/eventing/broker/README.md
> +Before you can use the Knative Channel-based Broker, you must install a channel provider, such as InMemoryChannel, RabbitMQ, Kafka or Nats.
```suggestion
Before you can use the Knative channel-based broker, you must install a channel provider, such as InMemoryChannel, RabbitMQ, Kafka or Nats.
```

2020-12-03 21:44 UTC, abrennan89 requested changes
If we're going to mention RabbitMQ, it should probably also be added here: https://knative.dev/docs/eventing/channels/channels-crds/ as an entry in the table.

We should try to keep this table in sync with the channel implementations we mention in this line probably, although I'm not sure we want to mention every single possible implementation here for "such as" - maybe just the core implementations, and add RabbitMQ to the table only?

WDYT @knative/eventing-wg-leads ?

2020-12-03 22:14 UTC, vaikas commented
Actually, there's no RabbitMQ channel yet, and as such you can't install a RabbitMQ channel and use it with the channel based broker. It should be a separate broker implementation like this here:
Section 4 in the installing eventing component:
```Install a Broker (eventing) layer:```

just like there's Kafka broker, we should have a RabbitMQ broker as a separate tab.

My most sincere apologies for not catching this sooner, I just added the ok-to-test and was going to go look at it, and totally spaced, I'm sorry :(

2020-12-04 14:46 UTC, abrennan89 commented
Ahhh I see @vaikas - that makes sense!
Don't worry about it at all, it's no problem :slightly_smiling_face: it didn't merge or anything yet anyway.

@xtreme-sameer-vohra I am going to close this PR though without merging since this isn't accurate, hope that's OK.

2020-12-04 14:46 UTC, closed without merging

2020-12-04 23:00 UTC, xtreme-sameer-vohra commented
Thanks for the clarification. 
I hadn't looked further to check if RabbitMQ had a Channel implementation 🤦