Update  ..sequence-with-broker-trigger/README.md
knative/docs pull request #3087
Opened 2020-12-07 02:15 UTC by xtreme-sameer-vohra

## Proposed Changes 
Remove duplicate statement in the wrong location
Reword incorrect statement

It makes sense to cherry-pick this to the release branch as well.

2020-12-07 13:31 UTC, abrennan89 commented on docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
> +configured your `Broker` & `Sequence`.
```suggestion
Change the `default` namespace below to create the PingSource in the namespace where you have
configured your broker and sequence.
```

2020-12-07 13:32 UTC, abrennan89 commented on docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
> +Change `default` below to create the `Trigger` in the Namespace where you have
```suggestion
Change `default` namespace below to create the trigger in the namespace where you have
```

2020-12-07 13:32 UTC, abrennan89 commented on docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
> +Then look at the logs for the sequence-display pod:
```suggestion
Look at the logs for the `sequence-display` pod:
```

2020-12-07 13:32 UTC, abrennan89 requested changes
Some minor comments :)

2020-12-07 17:13 UTC, abrennan89 commented
@xtreme-sameer-vohra I think you need to push again if you accepted comments because the CLA is weird, sorry! That should fix it though afaik.

2020-12-07 17:14 UTC, abrennan89 approved these changes
/lgtm
/hold

@knative/eventing-wg-leads can someone OK this from a technical perspective and remove the hold when you're ready? Thanks.

2020-12-07 17:19 UTC, xtreme-sameer-vohra commented
Hey @abrennan89 
I just went through the README.md and added a commit to make the language consistent across the page

re: the google cla, I wonder 🤔  if it can't properly handle the shared commits when I accepted your suggestions. In either case, I just pushed again

2020-12-15 12:35 UTC, pierDipi approved these changes
/lgtm

2020-12-15 12:36 UTC, pierDipi commented
/unhold

2020-12-15 12:46 UTC, merged