Add documentation to sinkbinding modes
knative/docs pull request #3101
Opened 2020-12-10 17:42 UTC by lberk

## Proposed Changes 

- Document the sinkbinding modes and their side effects in relation to namespaces and labels

2020-12-16 20:07 UTC, abrennan89 commented on docs/eventing/sources/sinkbinding.md
> +The selection mode determines the default scope of the webhook. By default, the upstream webhook is set to `exclusion` mode, which means any `Namespace` that does **not** have the label `bindings.kna
```suggestion
Sink binding operates in one of two modes; `Inclusion` or `Exclusion`.
You can set the mode by modifying the `SINK_BINDING_SELECTION_MODE` of the `eventing-webhook` deployment accordingly. The mode determines the default scope of the webhook.

By default, the webhook is set to `exclusion` mode, which means that any namespace that does not have the label `bindings.knative.dev/exclude: true` will be subject to mutation evalutation.

If `SINK_BINDING_SELECTION_MODE` is set to `inclusion`, only the resources in a namespace labelled with `bindings.knative.dev/include: true` will be considered.  In `inclusion` mode, any SinkBinding resource created will automatically label the `subject` namespace with `bindings.knative.dev/include: true` for inclusion in the potential environment variable inclusions.
```

2020-12-16 20:07 UTC, abrennan89 requested changes
@lberk just some edits :slightly_smiling_face:

2020-12-16 21:38 UTC, lberk commented
awesome, thanks @abrennan89! (though I think that means I just annoyed cla-bot and you might have to consent to me having used your edit?)

2020-12-16 21:46 UTC, lberk commented
@google-prow-robot I consent.

2020-12-16 21:46 UTC, lberk commented
@googlebot I consent.

2020-12-17 14:15 UTC, abrennan89 commented
@googlebot I consent

2020-12-17 14:16 UTC, abrennan89 commented
@lberk I think repushing the PR also works :slightly_smiling_face:

2020-12-17 14:17 UTC, abrennan89 approved these changes
/lgtm

2020-12-17 14:57 UTC, abrennan89 commented
Idk why this isn't working :confounded: @RichieEscarez can you please take a look in case it needs to be added manually? Are we missing something here?

2020-12-17 18:03 UTC, RichieEscarez commented
@abrennan89 are you on a different machine or maybe change your local config (ie [private account settings](https://knative.dev/community/contributing/contributing/#contributor-license-agreements))? The CLA is failing because of this email: `40172997+abrennan89@users.noreply.github.com`.

2020-12-17 19:01 UTC, abrennan89 commented
@RichieEscarez yes and no, my machine died so it had to be resurrected and reinstalled everything etc. Any idea how to fix that?

2020-12-17 19:52 UTC, lberk commented
@googlebot I consent.

@abrennan89 I edited the commit message to fix the email from github's auto-commit, sorry about that!

2020-12-17 19:53 UTC, abrennan89 commented
@googlebot I consent.

2020-12-17 19:57 UTC, abrennan89 commented
/lgtm

Please cla-bot :joy:

2020-12-17 20:08 UTC, merged