Add description table for install files for Knative Serving
knative/docs pull request #3296
Opened 2021-03-01 22:02 UTC by yanweiguo

Fixes #3274.

2021-03-01 22:03 UTC, yanweiguo commented
/assign @ZhiminXiang @dprotaso @ricardozanini 

cc @omerbensaadon

2021-03-02 00:05 UTC, ZhiminXiang commented
/lgtm

2021-03-02 00:13 UTC, yanweiguo commented
/assign @markusthoemmes

2021-03-02 13:14 UTC, omerbensaadon commented
/hold

2021-03-02 13:15 UTC, omerbensaadon commented
thank you @yanweiguo!! 

@snneji @RichardJJG can one of you give this a review?

2021-03-02 13:58 UTC, RichardJJG commented
@omerbensaadon, yep, will do.

2021-03-03 09:49 UTC, RichardJJG approved these changes
Needs a small change or two, which I'll take care of.

2021-03-03 11:05 UTC, RichardJJG requested changes
I'm new to GitHub reviews; ignore my last "approve" review. This one has all the changes I wanted to make.

2021-03-03 11:05 UTC, RichardJJG commented on docs/install/assets/serving.md
> +| serving-domainmapping-crds.yaml | CRDs required by the DomainMapping feature. | none |
| serving-domainmapping-crds.yaml | CRDs required by the Domain Mapping feature. | none |

2021-03-03 11:05 UTC, RichardJJG commented on docs/install/assets/serving.md
> +| serving-domainmapping.yaml | Componnents required by the DomainMapping feature. | serving-domainmapping-crds.yaml |
| serving-domainmapping.yaml | Components required by the Domain Mapping feature. | serving-domainmapping-crds.yaml |

2021-03-03 11:05 UTC, RichardJJG commented on docs/install/assets/serving.md
> +| serving-hpa.yaml | Components to auto scale Knative revisions via Kubeneters HPA. | serving-core.yaml |
| serving-hpa.yaml | Components to autoscale Knative revisions through the Kubernetes Horizontal Pod Autoscaler. | serving-core.yaml |

2021-03-03 11:05 UTC, RichardJJG commented on docs/install/assets/serving.md
> +| serving-post-install-jobs.yaml | Optional jobs after installing serving-core.yaml. Currently it is same to `serving-storage-version-migration.yaml`. | serving-core.yaml |
| serving-post-install-jobs.yaml | Optional jobs after installing serving-core.yaml. Currently it is the same as `serving-storage-version-migration.yaml`. | serving-core.yaml |

2021-03-03 11:05 UTC, RichardJJG commented on docs/install/assets/serving.md
> +| serving-storage-version-migration.yaml | Migrating the storage version of Knative resources, including Service, Route, Revision, Configuration, from v1alpha1 & v1beta1 to v1. Required by upgrade fr
| serving-storage-version-migration.yaml | Migrates the storage version of Knative resources, including Service, Route, Revision, and Configuration, from `v1alpha1` and `v1beta1` to `v1`. Required by upgrade from version 0.18 to 0.19. | serving-core.yaml |

2021-03-03 14:44 UTC, omerbensaadon commented
@markusthoemmes @davetropeano @yanweiguo see above changes by Richard! Thank you all :)

2021-03-03 18:57 UTC, yanweiguo commented
@RichardJJG PTAL

2021-03-04 10:11 UTC, snneji commented
/lgtm

2021-03-04 10:17 UTC, snneji commented
Whoops added the wrong label! I wanted to test using the Prow bot.

2021-03-04 15:08 UTC, dprotaso commented
looks good if we need further edits we can make a new PR

/lgtm
/approve
/hold cancel

2021-03-04 15:12 UTC, merged