Modify the instructions of the ingress configuration
knative/docs pull request #3301
Opened 2021-03-02 15:51 UTC by houshengbo

Fixes #issue-number or description of the problem the PR solves

## Proposed Changes 

-
-
-

2021-03-02 15:53 UTC, houshengbo commented
/assign @abrennan89

2021-03-02 20:48 UTC, abrennan89 commented
@houshengbo please assign someone who can give this a proper SME review instead, I don't think I'll be much help on this one
/unassign

2021-03-02 21:13 UTC, houshengbo commented
/assign @nak3 @evankanderson

2021-03-03 13:11 UTC, nak3 commented
/lgtm

2021-03-03 15:47 UTC, abrennan89 commented on docs/install/knative-with-operators.md
> +   There is no need to configure the ingress class to use the gloo.
```suggestion
   You do not need to configure the ingress class to use Gloo.
```

2021-03-03 15:47 UTC, abrennan89 requested changes
One small suggestion, otherwise lgtm

2021-03-03 19:27 UTC, evankanderson reviewed
/approve

2021-03-03 19:27 UTC, evankanderson commented on docs/install/knative-with-operators.md
> +   There is no need to configure the ingress class to use the gloo.
Maybe this is set by `glooctl`?

2021-03-03 19:30 UTC, merged

2021-03-03 20:32 UTC, houshengbo commented on docs/install/knative-with-operators.md
> +   There is no need to configure the ingress class to use the gloo.
we do not need it for gloo.
we only ship contour, kourier and istio.
for gloo, ambassador, kong, people can just configure and use. no need to set anything with knative.