Update knative-offerings.md
knative/docs pull request #3468
Opened 2021-04-16 13:07 UTC by omerbensaadon

Replace PCF with CNR for Tanzu

2021-04-19 16:50 UTC, abrennan89 commented on docs/knative-offerings.md
>  - [Red Hat Openshift Serverless](https://docs.openshift.com/container-platform/4.6/serverless/serverless-getting-started.html): enables stateful, stateless, and serverless workloads to all run on a s
```suggestion
- [Red Hat Openshift Serverless](https://docs.openshift.com/container-platform/4.7/serverless/serverless-getting-started.html): enables stateful, stateless, and serverless workloads to all run on a single multi-cloud container platform with automated operations. Developers can use a single platform for hosting their microservices, legacy, and serverless applications.
```

2021-04-19 16:50 UTC, abrennan89 commented on docs/knative-offerings.md
>  - [Red Hat Openshift Serverless](https://docs.openshift.com/container-platform/4.6/serverless/serverless-getting-started.html): enables stateful, stateless, and serverless workloads to all run on a s
Would you mind doing me a solid please and adding this suggestion to update the version for OCP? 🙏🏻

2021-04-19 16:51 UTC, abrennan89 commented on docs/knative-offerings.md
> +- [Cloud Native Runtimes for VMware Tanzu](https://docs.vmware.com/en/Cloud-Native-Runtimes-for-VMware-Tanzu/0.2/tanzu-cloud-native-runtimes-02/GUID-serverless-overview.html): is a serverless applica
```suggestion
- [Cloud Native Runtimes for VMware Tanzu](https://docs.vmware.com/en/Cloud-Native-Runtimes-for-VMware-Tanzu/0.2/tanzu-cloud-native-runtimes-02/GUID-serverless-overview.html): a serverless application runtime for Kubernetes that is based on Knative, and runs on a single Kubernetes cluster
```

2021-04-19 16:51 UTC, abrennan89 commented on docs/knative-offerings.md
> +- [Cloud Native Runtimes for VMware Tanzu](https://docs.vmware.com/en/Cloud-Native-Runtimes-for-VMware-Tanzu/0.2/tanzu-cloud-native-runtimes-02/GUID-serverless-overview.html): is a serverless applica
minor nit to make the formatting more consistent

2021-04-19 16:51 UTC, abrennan89 requested changes
Minor nits

2021-04-21 22:08 UTC, omerbensaadon commented
@abrennan89 see changes :)

2021-04-21 22:13 UTC, abrennan89 approved these changes
/lgtm

2021-04-21 22:16 UTC, merged