Move serving samples to index.md
knative/docs pull request #3469
Opened 2021-04-17 15:30 UTC by evankanderson

Remove `README.md` file includes for docs/serving/samples. I'm breaking these up into several PRs to make it easier to avoid conflicts / hold off on PRs that would have a conflict.

## Proposed Changes 

- Inline `README.md` files that are included via `{{readfile}}` shortcodes.

2021-04-17 15:33 UTC, evankanderson commented
/approve
/assign @julz @abrennan89 

(I'm assuming this makes `mkdocs` migration no harder and may simplify things overall.)

2021-04-17 16:36 UTC, julz commented
Yep, I currently have excludes set up in mkdocs.yml to hide all the index files with shortcodes, which this would let us drop, so \o/.

I'll let someone with more docs context lgtm, but lgtm :).

2021-04-19 13:22 UTC, abrennan89 commented on docs/serving/samples/cloudevents/cloudevents-dotnet/index.md
> -{{% readfile file="README.md" %}}
I think the filename needs to be `_index.md` like with the others?

2021-04-19 13:22 UTC, abrennan89 commented on docs/serving/samples/cloudevents/cloudevents-nodejs/index.md
> -{{% readfile file="README.md" %}}
same thing re filename 🙂

2021-04-19 13:23 UTC, abrennan89 requested changes
I think the filenames should be `_index.md` but not sure? A lot of them seem to be just `index.md`?

2021-04-19 15:54 UTC, evankanderson commented
Furthermore, an existence proof that these don't need to be `_index.md` is that the current site renders okay. 😁

2021-04-19 16:01 UTC, abrennan89 approved these changes
Ah, I got you 😄 in that case...

/lgtm
/approve

Thanks! 🙂

2021-04-19 16:02 UTC, merged