Slight change to ordered delivery guarantees
knative/docs pull request #3536
Opened 2021-05-06 06:23 UTC by matzew

Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

## Proposed Changes 

- slightly changing the doc for _ordered delivery guarantees_
-
-

2021-05-06 06:23 UTC, matzew commented
/assign @pierDipi 
/assign @slinkydeveloper

2021-05-06 06:33 UTC, pierDipi commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the Could Event receiver response before it delivers next messages of the partion.
typo: partition

2021-05-06 06:38 UTC, matzew commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the Could Event receiver response before it delivers next messages of the partion.
@pierDipi thanks, I updated

2021-05-06 06:42 UTC, pierDipi approved these changes
/lgtm

2021-05-06 10:34 UTC, slinkydeveloper requested changes

2021-05-06 10:34 UTC, slinkydeveloper commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the Could Event receiver response before it delivers next messages of the partition.
s/Could Event/CloudEvent

s/receiver/subscriber

2021-05-06 11:29 UTC, slinkydeveloper requested changes

2021-05-06 11:29 UTC, slinkydeveloper commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the CouldEvent subscriber response before it delivers next messages of the partition.
s/CouldEvent/CloudEvent

2021-05-06 15:02 UTC, slinkydeveloper approved these changes

2021-05-06 15:02 UTC, slinkydeveloper commented
/lgtm

2021-05-07 11:25 UTC, vaikas commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the CloudEvent subscriber response before it delivers next messages of the partition.
Does it have to be successful response?

2021-05-10 21:04 UTC, pierDipi commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the CloudEvent subscriber response before it delivers next messages of the partition.
Great question/suggestion.

2021-05-11 07:42 UTC, pierDipi approved these changes

2021-05-11 07:43 UTC, pierDipi commented
/lgtm

2021-05-12 10:11 UTC, vaikas commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the CouldEvent subscriber's successful response before it delivers next messages of the partition.
CouldEvent=>CloudEvent?

2021-05-14 18:21 UTC, abrennan89 commented on docs/eventing/broker/kafka-broker/_index.md
> +* `ordered`: Ordered consumer is a per-partition blocking consumer, waiting for the CouldEvent subscriber's successful response before it delivers next messages of the partition.
```suggestion
* `ordered`: An ordered consumer is a per-partition blocking consumer that waits for a successful response from the CloudEvent subscriber before it delivers the next message of the partition.
```

2021-05-14 18:21 UTC, abrennan89 commented on docs/eventing/broker/kafka-broker/_index.md
>  * `unordered`: Unordered consumer is a non-blocking consumer that potentially delivers messages unordered, while preserving proper offset management.
```suggestion
* `unordered`:  An  unordered consumer is a non-blocking consumer that delivers messages unordered, while preserving proper offset management.
```

2021-05-14 18:22 UTC, abrennan89 requested changes
Suggestions

2021-05-17 13:12 UTC, matzew commented
updated/rebased

2021-05-17 13:49 UTC, slinkydeveloper commented
/lgtm

2021-05-17 13:51 UTC, abrennan89 approved these changes

2021-05-17 13:52 UTC, merged