add rabbitmq to list of brokers
knative/docs pull request #3677
Opened 2021-05-27 11:31 UTC by vaikas

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

- Add pointers to RabbitMQ broker to install and available broker.
-
-

2021-05-27 15:20 UTC, snneji requested changes
A few small suggestions to improve the link text. Clear links are better for accessibility.

2021-05-27 15:20 UTC, snneji commented on docs/eventing/broker/README.md
> +The RabbitMQ Broker uses [RabbitMQ](https://www.rabbitmq.com/) for underlying implementation. For more details, refer to the [documentation](https://github.com/knative-sandbox/eventing-rabbitmq).
```suggestion
The RabbitMQ Broker uses [RabbitMQ](https://www.rabbitmq.com/) for its underlying implementation. For more information, see the [RabbitMQ broker](https://github.com/knative-sandbox/eventing-rabbitmq) in GitHub.
```

2021-05-27 15:20 UTC, snneji commented on docs/admin/install/install-eventing-with-yaml.md
> +    For more information, see the [RabbitMQ broker](https://github.com/knative-sandbox/eventing-rabbitmq).
```suggestion
    For more information, see the [RabbitMQ broker](https://github.com/knative-sandbox/eventing-rabbitmq) in GitHub.
```

2021-05-28 09:45 UTC, vaikas commented
Thanks! I addressed the feeback, ptal :)

2021-06-02 16:27 UTC, abrennan89 approved these changes
/lgtm

2021-06-02 16:54 UTC, merged