Add instruction for custom istio gateway
knative/docs pull request #3802
Opened 2021-06-15 03:14 UTC by nak3

This patch adds the instruction to use custom Istio Gateway.

Current doc has a similar instruction "customize Istio Gateway
Service". This doc is very similar but for "customize Istio Gateway".

Fix https://github.com/knative/docs/issues/3524

2021-06-15 07:43 UTC, nak3 commented
/cc @ZhiminXiang

2021-06-15 11:28 UTC, snneji requested changes
Hi @nak3, really good information in this PR. I've suggested a few changes so that the new information is formatted using Knative style rules, and is easier to understand.

2021-06-15 11:28 UTC, snneji commented on docs/serving/setting-up-custom-ingress-gateway.md
> +Update gateway configmap `config-istio` under `knative-serving`
```suggestion
Update the gateway ConfigMap `config-istio` under the `knative-serving`
```

2021-06-15 11:28 UTC, snneji commented on docs/serving/setting-up-custom-ingress-gateway.md
> +namespace:
```suggestion
namespace by running the command:
```

2021-06-15 11:28 UTC, snneji commented on docs/serving/setting-up-custom-ingress-gateway.md
> +The `GATEWAY_NAMESPACE` is optional. when it is omitted, the system will search for
```suggestion
The configuration format should be `gateway.<gateway-namespace>.<gateway-name>`.
`<gateway-namespace>` is optional. When it is omitted, the system searches for
```

2021-06-15 11:28 UTC, snneji commented on docs/serving/setting-up-custom-ingress-gateway.md
> +## Replace the knative-ingress-gateway gateway
```suggestion
## Replace the `knative-ingress-gateway` gateway
```

2021-06-15 11:28 UTC, snneji commented on docs/serving/setting-up-custom-ingress-gateway.md
> +#### Step 1: Create Gateway Service and Deployment Instance
The style in the Knative docs is to use sentence case in headings.

2021-06-15 11:31 UTC, snneji commented on docs/serving/setting-up-custom-ingress-gateway.md
> +The `GATEWAY_NAMESPACE` is optional. when it is omitted, the system will search for
Knative style rules say that placeholders should be in the format `<placeholder-name>` and not `PLACEHOLDER_NAME`.

2021-06-15 12:20 UTC, nak3 commented on docs/serving/setting-up-custom-ingress-gateway.md
> +the gateway in the serving system namespace `knative-serving`.
Sure! Let me try to change it.

2021-06-15 12:41 UTC, nak3 commented
Thank you @snneji ! Updated.

2021-06-15 16:15 UTC, ZhiminXiang reviewed
thanks for updating this doc @nak3!

2021-06-15 16:15 UTC, ZhiminXiang commented on docs/serving/setting-up-custom-ingress-gateway.md
> +1. Edit the file to replace the `istio-ingressgateway.istio-system.svc.cluster.local` field with
I feel "replace" might be confusing as we actually "add" a new field into "data" section.

2021-06-15 16:15 UTC, ZhiminXiang commented on docs/serving/setting-up-custom-ingress-gateway.md
> +1. Edit the file to replace the `gateway.knative-serving.knative-ingress-gateway` field with
same here. we may not want to use "replace".

2021-06-15 23:34 UTC, nak3 commented
Thank you Zhimin! updated.

2021-06-15 23:45 UTC, ZhiminXiang commented
/lgtm

2021-06-17 23:56 UTC, nak3 commented
@snneji Friendly ping. This is ready for merge, I think :smile_cat:

2021-07-07 13:50 UTC, omerbensaadon commented
/approve

2021-07-07 13:50 UTC, omerbensaadon commented
sorry for the delay @nak3, hit us in the #docs channel in the future 👍🏼

2021-07-07 14:02 UTC, merged