Added the benefit of deploy to knative service
knative/docs pull request #3884
Opened 2021-06-30 01:43 UTC by gyliu513

@markusthoemmes @evankanderson ^^

2021-07-02 11:04 UTC, snneji requested changes
Hi, I've added a few suggestions. 

I also think it would make sense to move this "Benefits" section to the top of the page, just before "Determine if your workload is a good fit for Knative". This is so that users can easily see the info they need to help them decide whether converting to a Knative Service is something they want to do.

2021-07-02 14:14 UTC, gyliu513 reviewed
Thanks @snneji

2021-07-02 14:14 UTC, gyliu513 commented on docs/serving/convert-deployment-to-knative-service.md
> +
Done

2021-07-02 14:14 UTC, gyliu513 commented on docs/serving/convert-deployment-to-knative-service.md
> +- Reduce footprint of the service instance as the instance will be scale to 0 when it becomes idle.
Done

2021-07-02 14:14 UTC, gyliu513 commented on docs/serving/convert-deployment-to-knative-service.md
> +- Performance can be improved via build-in autoscaling for knative service.
Done

2021-07-06 14:17 UTC, snneji commented
/lgtm

2021-07-07 13:43 UTC, abrennan89 approved these changes

2021-07-07 13:47 UTC, omerbensaadon commented
/retest

2021-07-07 13:52 UTC, merged