Add the instruction on how to configure the eventing sources with the operator
knative/docs pull request #3891
Opened 2021-06-30 17:23 UTC by houshengbo

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

2021-07-02 10:40 UTC, snneji requested changes
Looks good. Only a couple of tiny typos. 

Just a note, we have recently changed the way we document `kubectl apply` commands (for more info, see https://github.com/knative/docs/issues/3813 and [Documenting YAML](https://dev-knative.netlify.app/development/help/contributor/style-guide/documenting-code/#documenting-yaml) in the Style Guide). 

I am currently working on PRs to update all commands to the new format, so you can leave the commands as they are in this PR. I can update them as part of working on that issue.

2021-07-02 10:40 UTC, snneji commented on docs/admin/install/knative-with-operators.md
> +### Installing with Different Eventing Sources
Our style guide says that headings should be in sentence case not title case

2021-07-06 15:38 UTC, snneji commented
/lgtm

2021-07-07 14:16 UTC, omerbensaadon commented
/approve 

Created https://github.com/knative/docs/issues/3956 to address aligning to Style Guide

2021-07-07 14:26 UTC, merged

2021-07-07 18:56 UTC, houshengbo commented
/cherry-pick release-0.24