fixing broken links
knative/docs pull request #4014
Opened 2021-07-14 21:43 UTC by psschwei

Fixes #4013 

## Proposed Changes 

- Fixes broken links on docs/serving/knative-kubernetes-services.md page
(note that the first link here was circular... I assume it was meant to point to the readme)
- Fixes broken links in `DEVELOPMENT.md`

2021-07-16 17:11 UTC, abrennan89 approved these changes
/lgtm

2021-07-16 17:12 UTC, abrennan89 commented
/hold

2021-07-16 17:12 UTC, abrennan89 commented
@psschwei this looks like it needs a rebase, also, does this need to be cherrypicked to 0.24 as well?

2021-07-16 17:44 UTC, psschwei commented
Yes, this should be cherrypicked to 0.24, as the links are broken there as well

Will rebase shortly.

2021-07-16 17:54 UTC, psschwei commented
/hold

2021-07-16 18:04 UTC, psschwei commented
@abrennan89 I think the last two links (to website / maintainer help) on `DEVELOPMENT.md` have been sunset, maybe as part of #4020 or #4024 .  I wonder if it would be better for it to mirror the changes @RichardJJG made to `blog/README.md`?

2021-07-16 20:03 UTC, abrennan89 commented
Assigning @RichardJJG to take a look - might be better to rebase once any of his PRs are merged?

2021-07-16 20:28 UTC, psschwei commented
> @psschwei if this is undoing any of Richard's changes I'd just re-add whatever he did.

Not undoing any changes, at least I don't think it is. I think basically what's happening is:

- previously, the [`DEVELOPMENT.md`](https://github.com/knative/docs/blob/mkdocs/DEVELOPMENT.md) doc and the [`blog/README.md`](https://github.com/knative/docs/blob/21fe8c783ac0024d7b6f07cc3fc7f0e60d43255e/blog/README.md) doc were exactly the same
- in #4024, the `blog/README.md` doc was truncated to a single, main link, but `DEVELOPMENT.md` was not changed
- my question was whether the [`DEVELOPMENT.md`](https://github.com/knative/docs/blob/mkdocs/DEVELOPMENT.md) doc should also be truncated to the single main link to the "contributing to knative docs" documentation, like the [new `blog/README.md`](https://github.com/knative/docs/blob/mkdocs/blog/README.md)?

2021-07-22 21:11 UTC, abrennan89 commented
cc @omerbensaadon @RichardJJG to answer the comments / questions on this one please

2021-07-23 19:24 UTC, omerbensaadon commented
@psschwei it might be easier to revert changes to the DEVELOPMENT.md file and just ship the fix the linked issue is targeting

2021-07-23 19:28 UTC, omerbensaadon requested changes
I think if you remove this it should be good to merge? If you don't have any conflicts with Richard's changes, I'd /unhold. 

If you do, I'd take @RichardJJG's changes where there are conflicts.

2021-07-23 19:28 UTC, omerbensaadon commented on DEVELOPMENT.md
> +   * [Maintainer help](https://knative.dev/docs/help/maintainer/)
These pages don't exist anymore
```suggestion
```

2021-07-23 19:35 UTC, psschwei commented
It looks like #4054 also fixes the original broken links (and in a better way than my PR), so happy to close this one and let the other one merge instead.

(And apologies to @snneji  for forgetting to assign the issue)

2021-07-23 19:37 UTC, omerbensaadon commented
I think your PR still does fix some broken links in Development.MD as well as the blog README

2021-07-23 19:38 UTC, omerbensaadon commented
If you can 

1. Remove the last two lines from my review 
2. Remove changes covered by #4054 

We can get this merged

2021-07-26 11:22 UTC, RichardJJG commented
/lgtm

2021-07-26 13:46 UTC, RichardJJG commented
/approve

2021-07-26 13:57 UTC, psschwei commented
> /hold

Looks like both @abrennan89 and I put holds on this...  I'm good to remove mine.

2021-07-26 13:58 UTC, abrennan89 approved these changes
/lgtm
/unhold

2021-07-26 13:59 UTC, merged