eventing(samles): update Node.js CloudEvents ContainerSource example
knative/docs pull request #4039
Opened 2021-07-20 19:13 UTC by lance

## Proposed Changes 

The example had some old versions of Node and CloudEvents. This change
updates the versions for those dependencies, and makes some modifications
to the example code based on these dependency changes.

Signed-off-by: Lance Ball <lball@redhat.com>

2021-08-10 13:47 UTC, snneji requested changes

2021-08-10 13:47 UTC, snneji commented on docs/developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/README.md
> +image, and push it to a container registry accessible by our cluster.
```suggestion
Before publishing the ContainerSource, you must build the application
image, and push it to a container registry that your cluster can access.
```

2021-08-24 10:48 UTC, snneji commented
/ok-to-test

2021-08-31 19:36 UTC, abrennan89 commented on docs/developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/README.md
> +The sink URL where events are posted will be made available to the application through the `K_SINK` environment variable by the ContainerSource.
```suggestion
The sink URL where events are posted is made available to the application through the `K_SINK` environment variable, provided by the ContainerSource.
```

2021-08-31 19:37 UTC, abrennan89 approved these changes
/lgtm

One minor suggestion @lance but I don't think it's worth blocking this PR over. Thanks!

2021-08-31 19:46 UTC, merged