Ways to connect to cluster using kn
knative/docs pull request #4095
Opened 2021-08-02 17:49 UTC by vyasgun

Fixes: [#1251](https://github.com/knative/client/issues/1251)

## Proposed Changes 

- Adding information about `--kubeconfig`, `context`, and `config` options in `kn`

2021-08-03 07:28 UTC, dsimansk requested changes
I'd suggest to completely remove mentions of kn's `--config`flag and file, since there's detailed section about it and it might be confusing in context of connecting to cluster.
https://github.com/knative/docs/blob/mkdocs/docs/client/configure-kn.md

2021-08-05 08:00 UTC, dsimansk commented
Thanks @vyasgun! Looks good to me.
/lgtm

2021-08-09 12:39 UTC, snneji requested changes

2021-08-09 12:39 UTC, snneji commented on docs/client/README.md
> +Using the `kn` CLI, we can specify following options to connect to the cluster.
```suggestion
Using the `kn` CLI, you can specify the following options to connect to the cluster:

```

2021-08-09 12:39 UTC, snneji commented on docs/client/README.md
> +- `--kubeconfig` option is equivalent to setting the `$KUBECONFIG` environment variable and can be used to point to the kubeconfig file.
```suggestion
- `--kubeconfig`: use this option to point to the `kubeconfig` file. This is equivalent to setting the `$KUBECONFIG` environment variable.
```

2021-08-09 12:39 UTC, snneji commented on docs/client/README.md
> +- `--context` can be used to specify the name of a context from the existing kubeconfig. (One of the output list of: `kubectl config get-contexts`)
```suggestion
- `--context`: use this option to specify the name of a context from the existing `kubeconfig` file. Use one of the contexts from the output of `kubectl config get-contexts`.
```

2021-08-09 15:39 UTC, snneji commented
/lgtm
/approve

2021-08-10 10:23 UTC, snneji approved these changes

2021-08-10 11:53 UTC, snneji commented
/retest

2021-08-12 14:12 UTC, vaikas commented
/lgtm
/approve

2021-08-12 14:14 UTC, vaikas commented
/retest

2021-08-12 16:47 UTC, lionelvillard commented
/test pull-knative-docs-integration-tests

2021-08-12 17:04 UTC, merged

2021-08-12 18:48 UTC, snneji commented
Yay! Thanks for helping to get this merged!