add docs for byo certificate via domainmapping
knative/docs pull request #4104
Opened 2021-08-10 23:20 UTC by shinigambit

Fixes #4081

2021-08-11 04:36 UTC, nak3 reviewed
LGTM

2021-08-11 04:36 UTC, nak3 commented on docs/developer/serving/services/byo-certificate.md
> +
Should we add `{{ feature(beta="0.24") }}` like [Configuring custom domains section](https://github.com/knative/docs/blob/mkdocs/docs/developer/serving/services/custom-domains.md)?

2021-08-11 04:36 UTC, nak3 commented on docs/developer/serving/services/byo-certificate.md
> +    - `<tls-secret-name>` is the name of the TLS secret created in the previous step
nit
```suggestion
    - `<tls-secret-name>` is the name of the TLS secret created in the previous step.
```

2021-08-11 04:36 UTC, nak3 commented on docs/developer/serving/services/byo-certificate.md
> +    If the certificate is self-signed skip verification by adding the `-k` flag to curl
nit
```suggestion
    If the certificate is self-signed skip verification by adding the `-k` flag to curl.
```

2021-08-12 15:04 UTC, snneji requested changes
Very nice PR, thanks @shinigambit! I just added a few small suggestions. 

One more thing, do you think that it would make sense to mention on the autoTLS page that you can use a custom certificate instead?

2021-08-12 15:04 UTC, snneji commented on docs/developer/serving/services/byo-certificate.md
> +certificate to secure the mapped service, using this feature will skip _autoTLS_ certificate creation.
Also, do you think it would be nice to have a link to autoTLS here?

2021-08-12 18:07 UTC, shinigambit commented on docs/developer/serving/services/byo-certificate.md
> +- Same prerequisites as in [Configuring custom domains](../custom-domains) apply.
Thanks for your suggestions @snneji , I noticed that I put in the prerequisites an existing `TLS secret` but then in the procedure I put the steps to create one, so I simplified the requirement to just have a certificate. Let me know if it looks right

2021-08-18 12:11 UTC, snneji approved these changes

2021-08-18 12:20 UTC, merged