Style changes
knative/docs pull request #4156
Opened 2021-08-25 11:21 UTC by RichardJJG

Fixes #3876

2021-08-31 09:17 UTC, RichardJJG commented
> @RichardJJG did you find out whether the correct way to update the configmap in the second bullet of step 1 is using `kubectl -n <namespace> edit configmap <resource-name>`

I've reached out in Slack for that: https://knative.slack.com/archives/C93E33SN8/p1630401404010400

2021-08-31 18:37 UTC, abrennan89 commented on docs/developer/serving/services/custom-domains.md
> +    the private Knative Service is accessible from public internet with the custom domain of the domain mapping.
I'd use DomainMapping just to keep it consistent with the rest of the doc

2021-08-31 18:37 UTC, abrennan89 requested changes
Minor suggestion

2021-09-01 08:30 UTC, RichardJJG commented
> Minor suggestion

Done, thanks, @abrennan89!

2021-09-01 12:21 UTC, abrennan89 commented
/lgtm
/approve

@RichardJJG there's a hold label on this, not sure if you want me to remove and merge but lmk if you need anything else, you should be able to remove that label yourself 🙂

2021-09-01 12:53 UTC, RichardJJG commented
> /lgtm
> /approve
> 
> @RichardJJG there's a hold label on this, not sure if you want me to remove and merge but lmk if you need anything else, you should be able to remove that label yourself 🙂

@abrennan89, thanks, I forgot!

2021-09-01 13:02 UTC, merged