Add how to create custom domains with kn domain
knative/docs pull request #4209
Opened 2021-09-09 07:57 UTC by rhuss

## Proposed Changes 

- Add a description of how to leverage `kn domain` for managing custom domains
- Extended YAML description for `CustomDomain` include the `tls:` section for enabling HTTPS

Note, that I'm not sure about the formatting as I add the `kn` usage in the middle of a numbered list and am not sure how it will be rendered. Any help for fixing the formatting is appreciated. 

Fixes #3496

2021-09-09 11:30 UTC, snneji commented
Hi @rhuss, some of the formatting fixes will need to span lines that you have not edited in the PR so it will be difficult for me to use the suggestion feature to suggest the correct formatting. 

Would it be OK to merge the PR and then open a cleanup issue for us to fix the formatting and style for you? Or would you prefer me to leave comments on the PR for you to fix them yourself?

2021-09-09 13:37 UTC, rhuss commented
@snneji happy to merge it now and hand it over to you to fix the formatting. So maybe give it a quick look about whether the content is fine so far ?

2021-09-09 14:44 UTC, snneji requested changes
Looks OK to merge to me. Just a small fix here and the rest of the fixes can be dealt with in the cleanup issue. 

One other thing - does this PR need to be cherry picked? It seems to be based on an issue that was first created for v0.22.

2021-09-09 14:44 UTC, snneji commented on docs/developer/serving/services/custom-domains.md
> +    - `<target>` is the name of the Service or Route that is mapped to the domain. You can use a prefix `ksvc:` or `kroute:` to specify whether to map the domain to a Knative Service or Route. If no
```suggestion
    - `<target>` is the name of the Service or Route that is mapped to the domain. You can use a prefix `ksvc:` or `kroute:` to specify whether to map the domain to a Knative Service or Route. If no prefix is given, `ksvc:` is assumed. Additionally, you can use a `:namespace` suffix to point to a Service or Route in a different namespace than this Domain mapping. E.g. `mysvc` maps to a Service `mysvc` in the same namespace as this mapping, while `kroute:myroute:othernamespace` maps to a Route `myroute` in namespace `othernamespace`.
```

2021-09-09 16:15 UTC, rhuss commented
`kn` supports the `domain` command since 0.22, not sure about the `tls:` option though. @julz do you know when `tls:` was introduced to DomainMapping ? Was it there from the beginning ?

2021-09-10 10:06 UTC, julz commented
wasn't there in the beginning, looks like it [landed in 0.24](https://github.com/knative/serving/releases/tag/v0.24.0) (same time DM went beta)

2021-09-10 17:03 UTC, snneji commented
/lgtm

2021-09-10 17:06 UTC, snneji approved these changes

2021-09-10 17:06 UTC, snneji commented
Issue to fix formatting: https://github.com/knative/docs/issues/4225

2021-09-10 17:12 UTC, merged