Update accessing-traces.md
knative/docs pull request #4250
Opened 2021-09-15 23:46 UTC by xtreme-sameer-vohra

Fixes #4249 
Update instructions so they are general as opposed to Istio specific.

Happy to cherry-pick this for the 0.25 release if this gets merged before the next release is cut.

2021-09-16 10:51 UTC, snneji requested changes
Thanks for the PR! I think it might be easier for users to copy the addresses for the Zipkin and Jaeger UIs if they were in code boxes. 

Also, there is a whitespace error.

2021-09-16 10:51 UTC, snneji commented on docs/serving/accessing-traces.md
>  1.  Navigate to the
```suggestion
1. Access the Zipkin UI at the following URL:

    ```
    http://localhost:8001/api/v1/namespaces/<namespace>/services/zipkin:9411/proxy/zipkin/
    ```
    Where `<namespace>` is the namespace where Zipkin is deployed, for example, `knative-serving`.
```

2021-09-16 10:51 UTC, snneji commented on docs/serving/accessing-traces.md
> +    Replace `REPLACEME` in the link with the namespace where zipkin is deployed (eg. knative-serving).
```suggestion

```

2021-09-16 10:51 UTC, snneji commented on docs/serving/accessing-traces.md
> +    Replace `REPLACEME` in the link with the namespace where Jaeger is deployed (eg. knative-serving).
```suggestion
1.  Access the Jaeger UI at the following URL:

    ```
    http://localhost:8001/api/v1/namespaces/<namespace>/services/jaeger-query:16686/proxy/search/
    ```
    Where `<namespace>` is the namespace where Jaeger is deployed, for example, `knative-serving`.
```

2021-09-16 14:20 UTC, xtreme-sameer-vohra commented
> Thanks for the PR! I think it might be easier for users to copy the addresses for the Zipkin and Jaeger UIs if they were in code boxes.
> 
> Also, there is a whitespace error.

Thanks for the suggestions :)

2021-09-17 10:44 UTC, snneji approved these changes

2021-09-17 10:53 UTC, merged