Update the docs on configuring the knative-ingress-gateway gateway and istio-ingressgateway-service
knative/docs pull request #4297
Opened 2021-09-27 19:02 UTC by houshengbo

2021-09-28 10:24 UTC, snneji commented
/retest

2021-10-01 14:49 UTC, snneji requested changes
I've suggested a few small tweaks. 

I think new sections added in this PR could be laid out differently, for example:

```
## Replace the default istio-ingressgateway-service

1. Set up custom ingress gateway by following the instructions in [**Step 1: Create Gateway Service and Deployment Instance**](../../../serving/setting-up-custom-ingress-gateway.md/#step-1-create-the-gateway-service-and-deployment-instance).
2. Update `spec.ingress.istio.knative-ingress-gateway` to select the labels of the new ingress gateway: ...
3. Update the ingress gateway ConfigMap: ...
```

These changes cover lines that I cannot make a suggestion on so I can merge this PR and make a cleanup issue to make these style changes if you like.

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
> +The key in `spec.config.istio` is in the format of `gateway.{{gateway_namespace}}.{{gateway_name}}`.
```suggestion
The key in `spec.config.istio` is in the format of `gateway.<gateway-namespace>.<gateway-name>`.
```

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
>  The key in `spec.config.istio` is in the format of `gateway.{{gateway_namespace}}.{{gateway_name}}`.
```suggestion
The key in `spec.config.istio` is in the format of `gateway.<gateway-namespace>.<gateway-name>`.
```

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
> +The key in `spec.config.istio` is in the format of `gateway.{{gateway_namespace}}.{{gateway_name}}`.
The style guide says to use `<placeholder-name>` for placeholders instead of `{{placeholder_name}}`

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
> +## Replace default istio-ingressgateway-service
```suggestion
## Replace the default istio-ingressgateway-service
```

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
> +- [Replace default istio-ingressgateway service](#replace-default-istio-ingressgateway-service)
```suggestion
- [Replace the default istio-ingressgateway service](#replace-the-default-istio-ingressgateway-service)
```

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
> +To set up custom ingress gateway, follow [**Step 1: Create Gateway Service and Deployment Instance**](../../../serving/setting-up-custom-ingress-gateway.md/#step-1-create-the-gateway-service-and-depl
```suggestion
To set up a custom ingress gateway, follow [**Step 1: Create Gateway Service and Deployment Instance**](../../../serving/setting-up-custom-ingress-gateway.md#step-1-create-the-gateway-service-and-deployment-instance).
```

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
> +To create the ingress gateway, follow [**Step 1: Create the Gateway**](../../../serving/setting-up-custom-ingress-gateway.md/#step-1-create-the-gateway).
```suggestion
To create the ingress gateway, follow [**Step 1: Create the Gateway**](../../../serving/setting-up-custom-ingress-gateway.md#step-1-create-the-gateway).
```

2021-10-01 14:49 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
>  ### Step 2: Update the Knative gateway
```suggestion
2. Update `spec.ingress.istio.knative-ingress-gateway` to select the labels of the new ingress gateway:
```

2021-10-01 14:52 UTC, snneji commented on docs/admin/install/operator/configuring-serving-cr.md
>  ### Step 2: Update the Knative gateway
Ignore this suggestion. I cannot delete it for some reason.

2021-10-04 18:22 UTC, houshengbo commented
@snneji thx for the review.I think I can open another issue regarding the cleanup.

2021-10-06 17:46 UTC, merged

2021-10-06 17:47 UTC, snneji commented
Thanks @houshengbo! I've created an issue for the formatting changes here #4329.

/lgtm
/approve