Adding instructions on how to update blog
knative/docs pull request #4416
Opened 2021-11-02 16:50 UTC by psschwei

## Proposed Changes 

Adds a README for the blog that details how the blog works, how to make updates, etc.

/assign @omerbensaadon @csantanapr

2021-11-04 12:42 UTC, snneji requested changes
Found a few typos other than that, looks good to me. @csantanapr or @omerbensaadon would be better placed to comment on the completeness of the information provided.

2021-11-04 12:42 UTC, snneji commented on blog/README.md
> +What this means is that any changes to files in those directories (for example, updating the main site layout editing `docs/stylesheets/extra.css`) will go live _on the blog_ as soon as those changes
```suggestion
What this means is that any changes to files in those directories (for example, updating the main site layout editing `docs/stylesheets/extra.css`) will go live _on the blog_ as soon as those changes are pushed to `main`. In contrast, on the main site those changes will appear in the development branch and only go live when they are cherry-picked into the current release branch.
```

2021-11-04 12:42 UTC, snneji commented on blog/README.md
> +All fiels in `docs/overrides`, `docs/images`, and `docs/stylesheets` are copied to the blog at build-time.
```suggestion
All files in `docs/overrides`, `docs/images`, and `docs/stylesheets` are copied to the blog at build-time. 
```

2021-11-04 12:42 UTC, snneji commented on blog/README.md
> +For changes that are not top-level (i.e. adding a subsection to the "Getting started" guide or creating a new category of blog post), the change only needs to be made in the relevant section, as it's
```suggestion
For changes that are not top-level (i.e. adding a subsection to the "Getting started" guide or creating a new category of blog post), the change only needs to be made in the relevant section, as it's invisible to the other (for example, the subsection of the "Getting started" guide only needs to be made in `docs/config/nav.yml`)
```

2021-11-04 15:37 UTC, omerbensaadon commented
Going to follow these instructions now to post a new blog

2021-11-12 15:12 UTC, abrennan89 commented
@omerbensaadon any update on whether this can be merged? Can you do a review please?

2021-11-25 13:44 UTC, snneji commented
@omerbensaadon @csantanapr, would you like to review this PR? If not, since this is contributor and not user documentation, I think it's good enough to merge. If anyone has any issues with the procedure, they can submit a followup PR.

2021-12-01 13:32 UTC, snneji commented
Gonna merge, any changes necessary can go in a new PR.

/lgtm
/approve

2021-12-01 13:32 UTC, snneji approved these changes

2021-12-01 13:33 UTC, merged