Core Service as a Sink ref case added
knative/docs pull request #4459
Opened 2021-11-09 15:00 UTC by tzununbekov

Kubernetes core Service is a special case of Sinks. This PR adds an explanation of how destination ports are being chosen from single- and multi-port Service destinations.

## Proposed Changes

- `v1.Service` sink description added to the eventing/sinks doc

Do not merge until knative/pkg#2322 is merged.

2021-11-15 11:21 UTC, snneji requested changes

2021-11-15 11:21 UTC, snneji commented on docs/eventing/sinks/README.md
> +In all other cases or if the port specified in `knative.dev/destination-port` annotation does not exist in the service, sink URI resolution will fail.
```suggestion
In all other cases or if the port specified in `knative.dev/destination-port` annotation does not exist in the service, sink URI resolution will fail.
```
```suggestion
In all other cases, or if the port specified in `knative.dev/destination-port` annotation does not exist in the Service, Sink URI resolution fails.
```

2021-11-15 11:21 UTC, snneji commented on docs/eventing/sinks/README.md
> +The default protocol used in Sink URL is HTTP unless the destination port is 443 - in that case, HTTPS will be used as a URL scheme.
```suggestion
The default protocol used in Sink URL is HTTP unless the destination port is 443 - in that case, HTTPS will be used as a URL scheme.
```
```suggestion
The default protocol used in Sink URL is HTTP. If the destination port is 443, HTTPS is used as a URL scheme.
```

2021-11-15 11:21 UTC, snneji commented on docs/eventing/sinks/README.md
> +    \- _multi-port_ Service's port 80 will be used if it is exposed by the service.
```suggestion
    \- _single-port_ Service's only port will be used as a destination,

    \- _multi-port_ Service's port 80 will be used if it is exposed by the service.
```
```suggestion
    - For _single-port_: the Service's only port is used as a destination.

    - For _multi-port_: the Service's port 80 is used if it is exposed by the service.
```

2021-11-15 11:21 UTC, snneji commented
Just a few style tweaks, otherwise looks good to me.

2021-11-16 08:23 UTC, tzununbekov commented
@snneji thanks for the review, I've applied your suggestions. I believe this change must be on hold until knative/pkg#2322  is merged.

/hold

2021-11-17 12:58 UTC, snneji approved these changes

2021-12-09 21:09 UTC, abrennan89 commented
@tzununbekov any update on this one? It looks like the related pull request hasn't been updated in some time.

2021-12-13 08:21 UTC, tzununbekov commented
@abrennan89 yeah, I didn't have much time to work on this lately. Planning to get back to these PRs later this week.

2022-01-06 15:05 UTC, dprotaso commented
I resolved the conflict via the GitHub UI since it was trivial enough.

/lgtm

2022-01-06 15:07 UTC, dprotaso commented
Looks like the dependent pkg PR is still open - so keeping the hold

2022-02-09 19:04 UTC, csantanapr commented
after 3 months it looks this work is abandoned in https://github.com/knative/pkg/pull/2322
Feel free to reopen or open a new PR once the feature is implemented @tzununbekov

2022-02-09 19:04 UTC, closed without merging