Switch to snake-casing for config map properties
knative/docs pull request #4481
Opened 2021-11-12 20:39 UTC by dprotaso

- update casing for serving's config-deployment
- update casing for serving's config-network

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

2021-11-12 20:43 UTC, dprotaso commented
/cherry-pick release-1.0

2021-11-12 20:44 UTC, dprotaso commented
/assign @snneji

2021-11-15 11:05 UTC, snneji requested changes
Looks good. Just a few minor things I noticed for consistency. 

1. Should `autoTLS` always be `auto-tls`? I noticed a few of the former still remain in the docs. 
1. Just to confirm, this is only for  ConfigMaps right. There are a few occasions, for example, with `rollout-duration` where it is in camel case for the operator, but not for the config map.

2021-11-15 11:05 UTC, snneji commented on docs/serving/using-auto-tls.md
> +in the `knative-serving` namespace to enable `auto-tls`and specify how HTTP
```suggestion
in the `knative-serving` namespace to enable `auto-tls` and specify how HTTP
```

2021-11-15 21:19 UTC, dprotaso commented
> Should autoTLS always be auto-tls? I noticed a few of the former still remain in the docs.

I'll defer to you - the style guide has `autoTLS` as the preferred use. I just updated the PR so it's consistent.

> Just to confirm, this is only for ConfigMaps, right? 

Yes

> There are a few occasions, for example, with rollout-duration where it is in camel case for the operator, but not for the config map.

`spec` properties in the operator YAML should be `camelCase` - that's the general convention.

2021-11-16 16:31 UTC, snneji approved these changes

2021-11-16 16:32 UTC, merged