Mention optional attributes for CloudEvents in event sources overview
knative/docs pull request #4627
Opened 2022-01-11 19:47 UTC by lberk

This PR adds clarification that event sources which import messages from technologies such as Kafka, don't create/set optional attributes such as the contentdatatype.  That's a responsibility on the event producer.

2022-01-11 19:50 UTC, lance reviewed
/lgtm

2022-01-12 07:44 UTC, matzew approved these changes
:100: agree

/lgtm
/approve

2022-01-13 13:33 UTC, snneji requested changes
A few tweaks to follow the style guide.

2022-01-13 13:33 UTC, snneji commented on docs/eventing/sources/README.md
> +Please note: Event Sources which import events from other messaging technologies (such as Kafka or Rabbit) are not responsible for setting [Optional Attributes](https://github.com/cloudevents/spec/bl
```suggestion
!!! note
    Event Sources that import events from other messaging technologies such as Kafka or RabbitMQ are not responsible for setting [Optional Attributes](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#optional-attributes) such as the `datacontenttype`. This is a responsibility of the original event producer; the Source just appends attributes if they exist.
```

2022-01-14 16:30 UTC, lberk commented
Thanks @snneji! done!

2022-01-14 18:21 UTC, snneji approved these changes

2022-01-14 18:21 UTC, merged