Rewording the bits for the knative Kafka broker
knative/docs pull request #4687
Opened 2022-02-01 07:07 UTC by matzew

Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

## Proposed Changes 

- The term "Apache Kafka Broker" is very misleading as servers inside of a "Kafka cluster" are called brokers. Instead I change the header to "Knative Kafka Broker" to indicate a bit of differentiation between the actual Apache Kafka project and the Knative based implementation here  
-
-

2022-02-01 13:26 UTC, psschwei requested changes
Could you also update the title in the navigation https://github.com/knative/docs/blob/main/config/nav.yml#L193 ?

2022-02-01 15:41 UTC, snneji requested changes

2022-02-01 15:41 UTC, snneji commented on docs/eventing/broker/kafka-broker/README.md
> +The Knative Kafka Broker is a Apache Kafka native implementation of the Knative Broker API, that reduces
Building on what @psschwei spotted, I've noticed another tiny thing. Other than that LGTM from me as well.
```suggestion
The Knative Kafka Broker is an Apache Kafka native implementation of the Knative Broker API that reduces
```

2022-02-07 02:32 UTC, csantanapr commented
bump @matzew

2022-02-08 17:30 UTC, merged