Adds list of kn plugins to docs
knative/docs pull request #4804
Opened 2022-03-03 15:44 UTC by psschwei

## Proposed Changes 

Adds list of kn plugins and some details around installing them. Any suggestions welcome :) 

Fixes #4719

2022-03-04 21:54 UTC, psschwei commented
/retest

2022-03-07 13:10 UTC, snneji requested changes
Thanks for doing this one @psschwei -- the table looks really good! 🙂 

I have just a few questions and suggestions to add.

2022-03-07 13:10 UTC, snneji commented on docs/install/client/kn-plugins.md
> +Some plugins can be installed via the [Knative plugins Homebrew Tap](https://github.com/knative-sandbox/homebrew-kn-plugins/)) For example, the `kn-admin` plugin can be installed by running `brew ins
```suggestion
You can install some plugins can be installed using the [Knative plugins Homebrew Tap](https://github.com/knative-sandbox/homebrew-kn-plugins/). For example, you can install the `kn-admin` plugin by running `brew install knative-sandbox/kn-plugins/admin`.
```

2022-03-07 13:10 UTC, snneji commented on docs/install/client/kn-plugins.md
> +| [kn-plugin-admin](https://github.com/knative-sandbox/kn-plugin-admin) | Kn plugin for managing a Kubernetes based Knative installation | Y |
I think `kn` should be lower case and in code to be consistent.

2022-03-07 13:38 UTC, psschwei commented on docs/install/client/kn-plugins.md
> +All plugins can be installed by downloading the current release from Github and placing it somewhere on your `PATH`. You may need to rename the file to remove any OS/architecture information (for exa
+1 on making executable before moving.

As for the installation location, how about making the last instruction something like:
`Move the file to either a directory on your `PATH` or to the [`plugins/` directory](configure-kn.md) for your operating system.`?

2022-03-08 18:25 UTC, snneji commented on docs/install/client/kn-plugins.md
> +All plugins can be installed by downloading the current release from Github and placing it somewhere on your `PATH`. You may need to rename the file to remove any OS/architecture information (for exa
My only concern with giving 2 options is that uses might not know which to choose. Is there a best practice? If so, that's what we should document.

2022-03-08 18:38 UTC, psschwei commented on docs/install/client/kn-plugins.md
> +All plugins can be installed by downloading the current release from Github and placing it somewhere on your `PATH`. You may need to rename the file to remove any OS/architecture information (for exa
Got it. I think PATH is best practice, so will update to just include that option.

2022-03-10 14:28 UTC, snneji requested changes
Sorry, one more change to fix a link. Once you've applied the change ping me on Slack and I'll apply the LGTM.

2022-03-10 15:01 UTC, snneji commented
/lgtm

2022-03-10 15:02 UTC, merged