Fixed every broken formatting in knative serving guide
knative/docs pull request #4806
Opened 2022-03-03 19:47 UTC by hamees-sayed

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

2022-03-04 21:30 UTC, psschwei commented
/ok-to-test

2022-03-07 12:12 UTC, snneji requested changes
Just one small thing otherwise LGTM.

2022-03-07 12:12 UTC, snneji commented on docs/serving/using-auto-tls.md
> +  challenge. This component cannot be used with HTTP-01 challenge.
```suggestion
!!! warning
    Provisioning a certificate per namespace only works with DNS-01
    challenge. This component cannot be used with HTTP-01 challenge.
```

2022-03-07 13:41 UTC, hamees-sayed commented
@snneji done

2022-03-08 18:21 UTC, snneji commented
Thanks @hamees-sayed!

/lgtm
/approve

2022-03-08 18:21 UTC, snneji approved these changes

2022-03-08 18:23 UTC, merged