Fix broken formatting in Installing guide
knative/docs pull request #4917
Opened 2022-04-09 10:14 UTC by Subhasish-Behera

fixes #4477

2022-04-12 12:11 UTC, snneji commented
/ok-to-test

2022-04-12 12:45 UTC, snneji requested changes
Only one small tweak. Other than that it looks great. Thanks!

2022-04-12 12:45 UTC, snneji commented on docs/install/installing-istio.md
> +>   the pod status in realtime. You use `CTRL + C` to exit watch mode.
```suggestion
    You can append the `--watch` flag to the `kubectl get` commands to view
    the pod status in realtime. You use `CTRL + C` to exit watch mode.
```

2022-04-12 13:42 UTC, Subhasish-Behera commented
done

2022-04-15 11:00 UTC, snneji commented
Thanks for doing this one @Subhasish-Behera. 🙂

/lgtm
/approve

2022-04-15 11:02 UTC, merged