Include blog post for release-1.5
knative/docs pull request #5007
Opened 2022-06-06 18:06 UTC by dprotaso

Fixes: https://github.com/knative/docs/issues/4976#issuecomment-1146856965

2022-06-06 18:06 UTC, dprotaso commented
/assign @gab-satchi @csantanapr @snneji

2022-06-06 18:31 UTC, psschwei requested changes
some nits, mostly mkdocs related

2022-06-06 18:31 UTC, psschwei commented on blog/docs/releases/announcing-knative-v1-5-release.txt
> +- `kn` [CLI](#client)
```suggestion
- [`kn` CLI](#client)
```

2022-06-06 18:31 UTC, psschwei commented on blog/docs/releases/announcing-knative-v1-5-release.txt
> +- `kn` [CLI](#client)
(looks like the link has always been on just the CLI part, but in a vacuum I'd say it's better to link the whole line)

2022-06-06 18:31 UTC, psschwei commented on blog/docs/releases/announcing-knative-v1-5-release.txt
> +title: "1.5 release"
This doc also needs to be added to the blog navigation: https://github.com/knative/docs/blob/main/blog/config/nav.yml#L16

2022-06-06 18:31 UTC, psschwei commented on blog/docs/releases/announcing-knative-v1-5-release.txt
> +title: "1.5 release"
Doc should also be named `...release.md`

2022-06-06 18:31 UTC, psschwei commented on blog/docs/releases/announcing-knative-v1-5-release.txt
> +date: 06-06-2022
```suggestion
date: 2022-06-06
```

2022-06-06 19:27 UTC, dprotaso commented on blog/docs/releases/announcing-knative-v1-5-release.txt
> +date: 06-06-2022
I prefer YYYY-MM-DD

2022-06-06 19:34 UTC, psschwei commented
Think other than the lint fix, this one's good to go

2022-06-06 19:53 UTC, merged

2022-06-07 13:26 UTC, csantanapr commented
Thank you @dprotaso 🎉