Fixed markdown syntax in helloworld-java-spring/README.md
knative/docs pull request #5164
Opened 2022-08-08 22:58 UTC by hbelmiro

This PR fixes the syntax of `code-samples/serving/hello-world/helloworld-java-spring/README.md`, which is mixing Markdown and Asciidoc syntaxes.

2022-08-10 15:51 UTC, abrennan89 commented
@hbelmiro it's not actually asciidoc; we use Material for mkdocs to provide tabbed content. See https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-code-blocks

2022-08-10 15:53 UTC, abrennan89 commented
Leaving this PR open until we decide whether to contain these code samples in the website or just the repo. For the website the == formatting would be valid. If it's just staying in the repo we can merge this PR.

/hold
/ok-to-test

2022-08-23 10:27 UTC, snneji requested changes
Hi @hbelmiro, I added back some of the indentation removed as part of this PR because it is required to make the numbering format correctly. 

These code samples are in GitHub only at the moment so here's a link to for you to preview how this page looks: https://github.com/knative/docs/blob/bf85d69a192ed556c1e8956ea1b22ecbe341fdcd/code-samples/serving/hello-world/helloworld-java-spring/README.md (note the broken numbering in the Deploying the app and Verification sections).

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +Where `{username}` is your Docker Hub username.
```suggestion
    ```yaml
    apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: helloworld-java-spring
      namespace: default
    spec:
      template:
        spec:
          containers:
            - image: docker.io/{username}/helloworld-java-spring
              env:
                - name: TARGET
                  value: "Spring Boot Sample v1"
    ```
    Where `{username}` is your Docker Hub username.
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +Where `{username}` is your Docker Hub username.
Indentation required to make the numbering format properly. As you can see in [this preview](https://github.com/knative/docs/blob/bf85d69a192ed556c1e8956ea1b22ecbe341fdcd/code-samples/serving/hello-world/helloworld-java-spring/README.md#yaml), the numbering is broken.

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +**Note:** Ensure that the container image value in `service.yaml` matches the container you built in the previous step.
```suggestion
    **Note:** Ensure that the container image value in `service.yaml` matches the container you built in the previous step.
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +```
```suggestion
    ```bash
    kubectl apply -f service.yaml
    ```
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +**Note:** Ensure that the container image value in `service.yaml` matches the container you built in the previous step.
More indentation required for formatting.

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +### kubectl
```suggestion
    - For kubectl, run:
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +```
```suggestion
    ```bash
    kubectl get ksvc helloworld-java-spring  --output=custom-columns=NAME:.metadata.name,URL:.status.url
    ```
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +Example:
```suggestion
    Example:
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +```
```suggestion
    ```bash
    NAME                      URL
    helloworld-java-spring    http://helloworld-java-spring.default.1.2.3.4.xip.io
    ```
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +### kn
```suggestion
    - For kn, run:
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +```
```suggestion
    ```bash
    kn service describe helloworld-java-spring -o url
    ```
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +Example:
```suggestion
    Example:
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +```
```suggestion
    ```bash
    http://helloworld-java-spring.default.1.2.3.4.xip.io
    ```
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +Example:
```suggestion
    Example:
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +Hello Spring Boot Sample v1!
```suggestion
    ```bash
    curl http://helloworld-java-spring.default.1.2.3.4.sslip.io
    Hello Spring Boot Sample v1!
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +```
```suggestion
    # Even easier with kn:
    curl $(kn service describe helloworld-java-spring -o url)
    ```
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +**Tip:** Add `-v` option to get more detail if the `curl` command fails.
```suggestion
    **Tip:** Add `-v` option to get more detail if the `curl` command fails.
```

2022-08-23 10:27 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +### kn
I suggest removing the H3 heading here because these commands are part of a step.

2022-08-23 10:34 UTC, snneji commented
> Leaving this PR open until we decide whether to contain these code samples in the website or just the repo. For the website the == formatting would be valid. If it's just staying in the repo we can merge this PR.
> 

@abrennan89 We made the decision a while ago that it would be easier to maintain these code samples in GitHub and link out to them from the site. If you would like us to review this decision, we can discuss in the WG meeting.

2022-08-26 17:03 UTC, hbelmiro commented
Thanks for the review @snneji. I applied your suggestions.

2022-08-31 16:19 UTC, abrennan89 approved these changes
/lgtm

2022-08-31 16:20 UTC, merged

2022-08-31 16:22 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +    ```
```suggestion
        ```bash
        kn service describe helloworld-java-spring -o url
        ```
```

2022-08-31 16:22 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +    ```
```suggestion
        ```bash
        http://helloworld-java-spring.default.1.2.3.4.xip.io
        ```
```

2022-08-31 16:22 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +    Example:
```suggestion
        Example:
```

2022-08-31 16:22 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +    ```
```suggestion
        ```bash
        kubectl get ksvc helloworld-java-spring  --output=custom-columns=NAME:.metadata.name,URL:.status.url
        ```
```

2022-08-31 16:22 UTC, snneji commented on code-samples/serving/hello-world/helloworld-java-spring/README.md
> +    Example:
```suggestion
        Example:
```