Cleanup channel list
knative/docs pull request #5246
Opened 2022-09-26 19:10 UTC by lionelvillard

## Proposed Changes 

- Remove deprecated channels from the list to avoid confusion
- Change Support to Maintainer to better reflect Knative (or third-party) role.
- InMemory channel is "Stable" in a sense that it's compliant, maintained and does what it's supposed to do. 

/cc @pierDipi

2022-09-26 19:51 UTC, abrennan89 requested changes

2022-09-26 19:51 UTC, abrennan89 commented on docs/eventing/channels/channels-crds.md
> +
It was fine as it was, this block was the old frontmatter for Hugo and isn't needed now 🙂

2022-09-26 19:51 UTC, abrennan89 commented on docs/eventing/channels/channels-crds.md
> +  support.
same re notes, the `!!! note` format is correct, see https://github.com/knative/docs/blob/main/contribute-to-docs/getting-started/formatting.md#admonitions

2022-09-26 19:51 UTC, abrennan89 commented on docs/eventing/channels/channels-crds.md
> +>>>>>>> 1314d755 (Cleanup channel list)
some leftover bits from a rebase need to be removed 😉

2022-09-27 07:48 UTC, pierDipi commented
+1 for the idea!

2022-09-27 13:31 UTC, abrennan89 approved these changes
/lgtm

2022-09-27 13:32 UTC, merged