Extend event mesh topic
knative/docs pull request #5484
Opened 2023-03-16 18:48 UTC by evankanderson

Extend the prose from #5454 for event mesh

## Proposed Changes 

- Add more text for Knative event mesh
- Update image and include `.drawio` source

/cherrypick release-1.9

2023-03-16 18:50 UTC, evankanderson reviewed
/assign @matzew 

I can roll back the diagram if you want, but I wanted to try a slightly more dressed-up look.

2023-03-16 18:56 UTC, psschwei requested changes
a few of the links are broken... they need to go back up a level (didn't test below, but I think my suggestions should work)

2023-03-16 18:56 UTC, psschwei commented on docs/eventing/event-mesh.md
> +The above mentioned _event brokers_ map directly to a core API in Knative Eventing: the [`Broker` API](./brokers) offers a discoverable endpoint for event ingress and the [`Trigger` API](./triggers)
```suggestion
The above mentioned _event brokers_ map directly to a core API in Knative Eventing: the [`Broker` API](../brokers) offers a discoverable endpoint for event ingress and the [`Trigger` API](../triggers) completes the offering with its event filtering and delivery capabilities.  With these APIs Knative Eventing offers an Event Mesh as defined above:
```

2023-03-16 18:56 UTC, psschwei commented on docs/eventing/event-mesh.md
> +* **Events Ingress**: Support for connecting event senders: Source duck type and [SinkBinding](./custom-event-source/sinkbinding) to support easily configuring applications to deliver events to a `Br
```suggestion
* **Events Ingress**: Support for connecting event senders: Source duck type and [SinkBinding](../custom-event-source/sinkbinding) to support easily configuring applications to deliver events to a `Broker`.  Applications can submit events and use Eventing even without any sources installed.
```

2023-03-16 18:56 UTC, psschwei commented on docs/eventing/event-mesh.md
> +As visible in the above diagram, the Event Mesh is defined with the `Broker` and `Trigger` APIs for the ingress and the egress of events.  Knative Eventing enables multiple resources to participate i
```suggestion
As visible in the above diagram, the Event Mesh is defined with the `Broker` and `Trigger` APIs for the ingress and the egress of events.  Knative Eventing enables multiple resources to participate in the Event Mesh with a partial schema pattern called "duck typing".  Duck typing allows multiple resource types to advertise common capabilities, such as "can receive events at a URL" or "can deliver events to a destination".  Knative Eventing uses these capabilities to offer [a pool of interoperable sources](../sources) for sending events to the `Broker` and [as destinations for `Trigger`-routed events](../triggers).  The Knative Eventing APIs contain three categories of APIs:
```

2023-03-17 07:07 UTC, matzew commented on docs/eventing/event-mesh.md
> +An Event Mesh is dynamic infrastructure which is designed to simplify distributing events from senders to recipients.  Similar to traditional message-channel achitectures like Kafka or RabbitMQ, an E
For the first occurrence of `Kafka`, let's please use `Apache Kafka`, since that is the actual trademark from the ASF.

2023-03-17 08:14 UTC, matzew commented on docs/eventing/event-mesh.md
> +An Event Mesh is dynamic infrastructure which is designed to simplify distributing events from senders to recipients.  Similar to traditional message-channel achitectures like Kafka or RabbitMQ, an E
```suggestion
An Event Mesh is dynamic infrastructure which is designed to simplify distributing events from senders to recipients.  Similar to traditional message-channel architectures like Apache Kafka or RabbitMQ, an Event Mesh provides asynchronous (store-and-forward) delivery of messages which allows decoupling senders and recipients in time.  Unlike traditional message-channel based integration patterns, Event Meshes also simplify the routing concerns of senders and recipients by decoupling them from the underlying event transport infrastructure (which may be a federated set of solutions like Kafka, RabbitMQ, or cloud provider infrastructure).  The mesh transports events from producers to consumers via a network of interconnected _event brokers_ across any environment, and even between clouds in a seamless and loosely coupled way.
```

2023-03-21 16:10 UTC, evankanderson commented
Applied all requested changes.

2023-03-21 16:17 UTC, matzew approved these changes
/lgtm
/approve

2023-03-21 16:17 UTC, merged