Add knative serving in K0s blog
knative/docs pull request #5514
Opened 2023-03-26 23:50 UTC by naveenrajm7

Submitting blog post upon [invitation](https://github.com/knative/serving/issues/12718#issuecomment-1483805705) 

## Proposed Changes 

- Add knative serving in K0s blog

Originally done as part of [GSoC]( https://github.com/cncf/mentoring/blob/main/summerofcode/2022.md#make-knative-running-on-edge) [ proposal](https://gist.github.com/naveenrajm7/13261b01a662e2f515eb4e9bc203f5cb)

2023-03-27 07:08 UTC, ReToCode approved these changes
Nice, thank you.

/lgtm

/assign @csantanapr

2023-03-27 11:28 UTC, psschwei requested changes
There's a bunch of links that aren't working (possibly because they have a `--` in them, but can't say for sure that's the issue). I've tried to note all the ones I found, but you may want to double check them all in case I missed one.

2023-03-27 11:28 UTC, psschwei commented on blog/docs/articles/knative-serving-in-k0s.md
> +This document has three sections. In first section we capture the resource required by knative serving and K0s. In second section we monitor the actual resource used by Knative and K0s, to determine
link here isn't working

2023-03-27 11:28 UTC, psschwei commented on blog/docs/articles/knative-serving-in-k0s.md
> +    * [Knative Default Resource Requirement](#knative--k0s-default-resource-requirement)
this one too

2023-03-27 11:28 UTC, psschwei commented on blog/docs/articles/knative-serving-in-k0s.md
> +    * [Knative + K0s Default resource requirement](#knative--k0s-default-resource-requirement)
this one too

2023-03-27 11:28 UTC, psschwei commented on blog/docs/articles/knative-serving-in-k0s.md
> +    * [Knative + K0s resource usage](#knative--k0s-resource-usage)
this one too

2023-03-27 11:28 UTC, psschwei commented on blog/docs/articles/knative-serving-in-k0s.md
> +>\*  default-domain is a Job, and the resource will be freed up once the job completes
may want to use an [admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types) here

2023-03-27 11:28 UTC, psschwei commented on blog/docs/articles/knative-serving-in-k0s.md
> +Though reducing by 50% might seem random, when I tried to install the default files , some pods didn't come up due to insufficient CPU. The mimimum request of 890 milli core (see [Knative Default Res
this link isn't working

2023-03-28 12:32 UTC, psschwei approved these changes
Thanks!

/lgtm
/approve

2023-03-28 12:33 UTC, merged