Explain what `sample application` is, in `no-dns.md`
knative/docs pull request #5676
Opened 2023-09-11 13:48 UTC by ofey404

This PR is a documentation enhancement. It adds the missing reference to the sample application.

## Proposed Changes 

![image](https://github.com/knative/docs/assets/35857538/3e05622f-84b8-4332-b5d4-58d2ff1b9032)

The `helloworld-go application` here is a backward reference, as a newcomer, I have no idea where it is.

So I added a `tip` section, linking to the first service page - https://knative.dev/docs/getting-started/first-service/

2023-09-18 10:14 UTC, pierDipi commented
/cc @dprotaso

2023-09-20 06:56 UTC, ReToCode requested changes
I see your point. I think the first sentence here tries to say, you can deploy your own web-application with Knative to verify your setup or use the sample application.

How about if add a link to the `sample application` in the first sentence of that paragraph: 

> If you are using `curl` to access the sample applications, or your own Knative app

2023-10-07 06:20 UTC, ofey404 commented
> How about if add a link to the `sample application` in the first sentence of that paragraph:

Good idea. It doesn't change the original doc and make things more concise.

2023-10-19 13:29 UTC, ReToCode approved these changes
Looks good, thanks!

/lgtm
/approve

2023-10-19 13:31 UTC, merged