Add security audit report and blogpost
knative/docs pull request #5775
Opened 2023-11-27 20:51 UTC by AdamKorcz

Adds the Knative security audit report and blogpost.

cc @davidhadas @evankanderson

2023-11-28 07:15 UTC, ReToCode commented
PTAL:

/assign @evankanderson 
/assign @davidhadas

2023-11-28 07:38 UTC, davidhadas commented on blog/docs/events/security-audit-2023.md
> +One CVE was assigned during the audit for a vulnerability that could allow an attacker with already escalated privileges to cause further damage in the cluster. The attacker needs to first establish
```suggestion
One CVE was assigned during the audit for a vulnerability that could allow an attacker with already escalated privileges to cause further damage in the cluster. The attacker needs to first establish a position in a Knative pod, and from there, they could exploit the vulnerability and cause denial of service of the Knative autoscaling, thereby denying any autoscaling of Knative. The issue was assigned CVE-2023-48713 of Moderate severity and has been fixed in v1.10.5, v1.12.0 and v1.11.3.
```

2023-11-28 14:00 UTC, davidhadas commented on blog/docs/events/security-audit-2023.md
> +The auditors recommend that Knative adopt the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator), an official SLSA-maintained project. slsa-github-generator ensures tamp
@AdamKorcz 

It seems that the recommendations related to `slsa-github-generator` is a generic recommendation - not related to this audit or this blog post. 

How about creating a separate blog post on this issue and providing the background and the recommendation for Knative to head in this direction? I am not sure if it makes sense that it will be part of this audit report post.

2023-11-28 17:03 UTC, dprotaso commented on blog/docs/events/security-audit-2023.md
> +The auditors recommend that Knative adopt the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator), an official SLSA-maintained project. slsa-github-generator ensures tamp
cc @upodroid you've done a bunch of stuff related to SLSA no? eg. signing right?

2023-11-28 17:05 UTC, dprotaso requested changes
There are typos in the PDF.

eg. under thread modelling you have 'Knative Serving' but then the paragraphs under neath it talk about Knative Eventing

Then under the `Knative Serving` section there are phrases like `Knative Eventing will autoscale` - but it should be 'Knative Serving'

2023-11-28 19:00 UTC, AdamKorcz commented on blog/docs/events/security-audit-2023.md
> +The auditors recommend that Knative adopt the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator), an official SLSA-maintained project. slsa-github-generator ensures tamp
@davidhadas If it is up to me, then I say keep it. It is an outcome of the audit and also a great thing that contributors can work on.

2023-11-28 19:03 UTC, AdamKorcz commented
> There are typos in the PDF.
>
> eg. under thread modelling you have 'Knative Serving' but then the paragraphs > under neath it talk about Knative Eventing
>
> Then under the Knative Serving section there are phrases like Knative Eventing will > autoscale - but it should be 'Knative Serving'

Thanks for catching that. Should now be fixed with the latest report.

2023-12-04 18:03 UTC, evankanderson commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
Feel free to include this, but Knative is using [Prow](https://github.com/kubernetes/test-infra/tree/master/prow) to build and test releases (our usage requires more resources than are available on GitHub Actions, including real Kubernetes clusters).  As such, the GitHub Actions SLSA generator is probably not a good fit.

We're also using [`ko`](https://github.com/ko-build/ko) to build these releases, which doesn't currently have signing support (see https://github.com/ko-build/ko/issues/357 and https://github.com/ko-build/ko/issues/603).

2023-12-04 18:04 UTC, evankanderson commented on blog/docs/events/security-audit-2023.md
> +Knative is an open-source project that encourages community contributions. If you wish to contribute to Knative’s ongoing security work, we recommend that you read through the report, in particular t
Given that we're not using GitHub Actions to build our releases, I'm not sure we should steer people towards the `slsa-github-generator`.  (If we were, that would be a great tool.)

```suggestion
Knative is an open-source project that encourages community contributions. If you wish to contribute to Knative’s ongoing security work, we recommend that you read through the report, in particular the strategic recommendations and the SAST tooling section, which both include practical recommendations for Knative’s security posture. If you have questions, comments or suggestions, you can [engage with the community in several ways](https://knative.dev/docs/community/).
```

2023-12-04 18:05 UTC, evankanderson commented
(Other than the comments on our builds not being done via GitHub Actions, this LGTM.)

2023-12-04 19:51 UTC, evankanderson commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
Huh, it turns out that _Knative Serving_ does not have attestations, but most of the other releases do.  For example:

```
cosign download attestation $(curl -L https://github.com/knative/eventing/releases/download/knative-v1.12.1/eventing-core.yaml | grep image: | head -1 | cut -d: -f2-)
```

(Grab the first image from the Eventing release and run `cosign download attestation` on it...)

2023-12-04 19:52 UTC, evankanderson commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
(And append ` | jq -r '.payload' | base64 --decode | jq` to read the actual in-toto attestation, rather than the base64-encoded envelope)

2023-12-04 20:26 UTC, evankanderson commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
https://github.com/knative/infra/issues/287 for the attestations for serving.

2023-12-04 20:38 UTC, evankanderson commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
```suggestion
```

2023-12-04 20:38 UTC, evankanderson commented
(If you're willing to accept the two strikeouts on provenance information, I'm willing to publish this.)

2023-12-04 23:12 UTC, AdamKorcz commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
I would prefer to change that paragraph to mention Knatives good work on generating SLSA-compliant provenance than removing it. I have changed the paragraph in https://github.com/knative/docs/pull/5775/commits/b93cf114252ba04282d8a238cec99513350f7979

2023-12-04 23:12 UTC, AdamKorcz commented on blog/docs/events/security-audit-2023.md
> +The auditors found that Knative does not include provenance with releases; Provenance is a critical component of complying with [SLSA](https://slsa.dev/)  and ensuring tamper resistance of release ar
I have also changed the executive summary and SLSA sections of the report to reflect this.

2023-12-05 00:14 UTC, AdamKorcz commented
@evankanderson PTAL

2023-12-05 04:16 UTC, evankanderson reviewed
/lgtm
/approve

2023-12-05 04:18 UTC, merged