Resolved the bug in the default styling of note
knative/docs pull request #5812
Opened 2024-01-05 07:35 UTC by professorabhay

Fixes #5810 

- Solved the bug.

![image](https://github.com/knative/docs/assets/76243309/6d12f028-182d-47c7-ae52-88ae8b748fcd)

2024-01-05 09:24 UTC, ReToCode requested changes

2024-01-05 09:24 UTC, ReToCode commented on docs/eventing/configuration/broker-configuration.md
> +    Be aware that different Broker classes usually require different configuration ConfigMaps. Seethe configuration options of the different [Broker implementations](../brokers/broker-typesREADME.md)
There are some blanks missing now I think.

/hold

2024-01-05 09:54 UTC, professorabhay commented
I think it's rendering pretty fine right now.

![image](https://github.com/knative/docs/assets/76243309/c68f7610-46c6-4703-a5cd-187fb6ea9a04)

2024-01-05 10:15 UTC, ReToCode commented
Rendering is fine now, but the links are not working:

```
WARNING -  Doc file 'eventing/configuration/broker-configuration.md' contains a relative link '../brokers/broker-typesREADME.md', but the target 'eventing/brokers/broker-typesREADME.md' is not found among documentation files.
WARNING -  Doc file 'eventing/configuration/broker-configuration.md' contains a relative link '../brokers/broker-typeskafka-broker/README.md#configure-a-kafka-broker', but the target 'eventing/brokers/broker-typeskafka-broker/README.md' is not found among documentation files.
```

2024-01-05 12:04 UTC, professorabhay commented
Thanks for pointing out. I'll make sure it resolves in the next commit.

2024-01-05 14:52 UTC, professorabhay commented
It's working fine.

2024-01-08 06:44 UTC, ReToCode approved these changes
Thank you.

/lgtm
/approve
/unhold

2024-01-08 06:44 UTC, ReToCode commented
/cherry-pick release-1.12

2024-01-08 06:46 UTC, merged