new design implementation for footer and removed the pre-footer section
knative/docs pull request #6036
Opened 2024-07-01 13:03 UTC by ShravaniAK

resolves #6035 

changes made :
1. replaced the footer background colour.
2. Move footer icons to the right.
3. Remove the pre-footer section of the previous design.
4. added space at the top of the cncf logo container.

proposed design :
<img width="1011" alt="Screenshot 2024-07-01 at 6 30 29 PM" src="https://github.com/knative/docs/assets/97099574/b9cf3409-94c0-4e8b-8534-eb93fba4a876">

Implementaion:

<img width="1439" alt="Screenshot 2024-07-01 at 6 30 45 PM" src="https://github.com/knative/docs/assets/97099574/a6b1752c-6332-46db-92a1-d080a5ad2885">

2024-07-02 12:59 UTC, Cali0707 requested changes

2024-07-02 12:59 UTC, Cali0707 commented on docs/stylesheets/extra.css
> +  margin:0.5rem 1.5rem;
nit:
```suggestion
  display: flex;
  flex-direction: row;
  margin: 0.5rem 1.5rem;
```

2024-07-02 12:59 UTC, Cali0707 commented on docs/stylesheets/extra.css
> +  --md-footer-bg-color:#081729;
nit:
```suggestion
  --md-footer-bg-color: #081729;
```

2024-07-12 06:33 UTC, ShravaniAK commented
@Cali0707 I have fixed the spacing issue , thanks !

2024-07-12 12:31 UTC, Cali0707 requested changes
Nice work @ShravaniAK - this looks a lot better now! I left one code quality comment and then we should be good to merge this

2024-07-12 13:15 UTC, ShravaniAK commented on docs/stylesheets/extra.css
> +} */
yes done !

2024-07-17 06:14 UTC, ShravaniAK commented
@Cali0707 I have removed the commented code, thanks.

2024-07-17 13:48 UTC, Cali0707 approved these changes
/lgtm
/approve

2024-07-17 13:49 UTC, merged