add documentation for running knative on IBM s390x/IBM ppc64le platforms
knative/docs pull request #6043
Opened 2024-07-08 08:06 UTC by dilipgb

This document updates the installation steps needed to install knative on IBM s390x and IBM ppc64le platforms.

2024-07-08 19:39 UTC, davidhadas commented
I find the doc confusing:
1. It is unclear how Kourier differ from "3-scale-kourier-gateway" 
2. It is unclear how to merge the instructions provided to the "3-scale-kourier-gateway" with those already shown for Kourier

I would suggest taking a straight forward approach and stating in the Note something like: "Use [this alternative documentation](https://deploy-preview-6043--knative.netlify.app/docs/install/yaml-install/serving/install-serving-with-yaml-on-IBM-Z-and-IBM-P/) to install a networking layer on IBM Z and IBM Power platforms."

Then in the documentation, I would suggest to include all steps needed to get to a working networking layer. 

Instead of "Customizing 3-scale-kourier-gateway on IBM Z and IBM P platform" as a header, I would use "Install a networking layer on IBM Z and IBM Power platforms."

Instead of "To run 3-scale-kourier-gateway on IBM Z and IBM P platforms, ..." I suggest "To install a networking layer on IBM Z and IBM P platforms, ..." and spell out the steps to do that

2024-07-09 07:07 UTC, dilipgb commented
@davidhadas **3-scale-kourier-gateway** is the deployment name for kourier gateway deployed as part of the kourier deployment. I used the same deployment name, so users who face issues pulling images can relate to.

I will create a single document instead of redirecting user multiple times to different documentations. But there is no difference between standard deployment and deployment we are suggesting. We are patching the image for the same deployment that is done via standard knative scripts.

2024-07-09 09:56 UTC, dilipgb commented
@davidhadas can you please review and let me know if this looks good? I updated the document to be more readable and why we need to patch the 3-scale-kourier-gateway.

2024-07-14 20:38 UTC, davidhadas requested changes
Please consider the below suggested changes.
Please verify that the provided instructions and overall guidance are correct and accurate.

2024-07-14 20:38 UTC, davidhadas commented on docs/install/yaml-install/serving/install-serving-with-yaml-on-IBM-Z-and-IBM-P.md
> +  Patch the deployment **deploy/3-scale-kourier gateway in kourier-system namespace** with latest available image from [redhat catalog](https://catalog.redhat.com/software/containers/openshift-servic
```suggestion
This additional step is required for installing the Kourier networking layer on IBM Z and IBM Power platforms.

Once you completed installing Kourier,  patch the envoy image as described below. Use the envoy image included as part of the (RedHat Maistra)[https://maistra.io/] distribution. Maistra is an opinionated distribution of Istio designed to work with OpenShift and is supported on IBM Z and IBM Power platforms.

1. Find the image name to use:  
1a. Access the [redhat catalog](https://catalog.redhat.com/software/containers/openshift-service-mesh/proxyv2-rhel8/5d2cda455a134672890f640a) 
1b. Choose the appropriate architecture (ppc64le/s390x) from the architecture drop down. 
1c. Choose the latest tag from the list of available tags at the tag dropdown
1d. Click on the "get this image" tab and copy the image name. For example: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:ced904...`

2. Patch the **3scale-kourier-gateway**  deployment in **kourier-system** namespace with latest available image using **kubectl** as shown below.
```

2024-07-14 20:38 UTC, davidhadas commented on docs/install/yaml-install/serving/install-serving-with-yaml-on-IBM-Z-and-IBM-P.md
> +    '{"spec":{"template":{"spec":{"containers":[{"name":"kourier-gateway" "image":"<replace the proxyv2 image here>"}]}}}}'
```suggestion
    '{"spec":{"template":{"spec":{"containers":[{"name":"kourier-gateway" "image":"<the proxyv2 image name>"}]}}}}'
```

2024-07-14 20:38 UTC, davidhadas commented on docs/install/yaml-install/serving/install-serving-with-yaml.md
> +    Follow the below steps to install kourier. Post installation, [Use this alternative documentation](./install-serving-with-yaml-on-IBM-Z-and-IBM-P.md) to patch envoy image since we do not have env
```suggestion
    Follow the below steps to install Kourier. Post installation, patch the envoy image based on RedHat Maistra as described in [this link](./install-serving-with-yaml-on-IBM-Z-and-IBM-P.md).
```

2024-07-15 13:12 UTC, dilipgb commented
@davidhadas I think sub point in docs/install/yaml-install/serving/install-serving-with-yaml-on-IBM-Z-and-IBM-P.md is not rendering properly in the deploy preview. I will see how to add them in markup and commit it.

2024-07-15 13:47 UTC, dilipgb commented
@davidhadas I have corrected the alignment. Can you please review it again?

2024-07-21 13:38 UTC, davidhadas commented on docs/install/yaml-install/serving/install-serving-with-yaml-on-IBM-Z-and-IBM-P.md
> +Once you completed installing Kourier,  patch the envoy image as described below. Use the envoy image included as part of the (RedHat Maistra)[https://maistra.io/] distribution. Maistra is an opinion
```suggestion
Once you completed installing Kourier,  patch the envoy image as described below. Use the envoy image included as part of the [RedHat Maistra](https://maistra.io/) distribution. Maistra is an opinionated distribution of Istio designed to work with OpenShift and is supported on IBM Z and IBM Power platforms.
```

2024-07-21 13:46 UTC, davidhadas commented
/lgtm
@skonto, @Cali0707 can you pls have a look?

2024-07-21 13:47 UTC, davidhadas approved these changes

2024-07-21 13:49 UTC, merged